import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { after, before, test } from 'node:test'
import Database from 'better-sqlite3'
import { estimateTokenCost } from '../src/pricing.js'

const dir = mkdtempSync(join(tmpdir(), 'orchestrator-test-'))
const path = join(dir, 'test.db')
process.env.ORCHESTRATOR_DB = path
const { migrate } = await import('../src/db/migrate.js')
migrate(path)
const { base, uid } = await import('../src/db/index.js')
const { createServer } = await import('../src/server.js')
const { exportJournal, exportObject } = await import('../src/db/export.js')
const { importBundle } = await import('../src/db/import.js')
const { evidenceName, journalName } = await import('../src/sync.js')
const { addDeclaredEvidence, readTracking, recordObservation, setTracking, trackingStatus } = await import('../src/tracking.js')
let server, origin, project

test('public rate card estimates API-equivalent costs',()=>{assert.equal(estimateTokenCost('gpt-5.6-sol',{input_tokens:1_000_000,cached_tokens:500_000,output_tokens:100_000}).amount,5.75);assert.equal(estimateTokenCost('claude-sonnet-4',{input_tokens:1_000_000,output_tokens:100_000}).amount,4.5);assert.equal(estimateTokenCost('unknown-model',{input_tokens:1_000_000}),null)})

before(async () => {
  project = { uid: uid(), slug: 'test', name: 'Test' }
  base().prepare('INSERT INTO projects(uid,slug,name) VALUES(?,?,?)').run(project.uid,project.slug,project.name)
  server = createServer().listen(0,'127.0.0.1')
  await new Promise((resolve)=>server.once('listening',resolve))
  origin=`http://127.0.0.1:${server.address().port}`
})
after(async()=>{ await new Promise((resolve)=>server.close(resolve)); rmSync(dir,{recursive:true,force:true}) })

test('migration is idempotent and valid',()=>{ assert.equal(migrate(path).migrated,false); const db=new Database(path,{readonly:true}); assert.equal(db.pragma('integrity_check',{simple:true}),'ok'); assert.deepEqual(db.pragma('foreign_key_check'),[]); db.close() })
test('system health reports database integrity without mutation',async()=>{const before=base().prepare('SELECT count(*) n FROM events').get().n,response=await fetch(`${origin}/api/system/health`),data=await response.json();assert.equal(response.status,200);assert.equal(data.ok,true);assert.equal(data.execution,false);assert.equal(data.database.integrity,'ok');assert.equal(data.database.foreign_key_violations,0);assert.ok(Number.isFinite(data.database.bytes));assert.ok(Array.isArray(data.backups));assert.equal(base().prepare('SELECT count(*) n FROM events').get().n,before)})
test('events are idempotent and append-only',async()=>{
  const body={project:'test',kind:'event.recorded',actor_kind:'codex',actor:'Codex',assertion:'agent_statement',summary:'Observed state'}
  const first=await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'same'},body:JSON.stringify(body)})
  const second=await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'same'},body:JSON.stringify(body)})
  assert.equal(first.status,201); assert.equal(second.status,200); assert.equal(base().prepare('SELECT count(*) n FROM events').get().n,1)
  assert.throws(()=>base().prepare('UPDATE events SET summary=?').run('changed'),/append-only/)
})
test('project tracking commands are portable, passive and enforce disable',async()=>{const root=join(dir,'cli-project');mkdirSync(root);let state=setTracking(true,{root,project:'cli-project',name:'CLI Project'});assert.equal(state.enabled,true);assert.equal(readTracking(root).evidence_mode,'declared-only');assert.equal(trackingStatus(root).project.status,'active');const fixture=join(root,'proof.txt');writeFileSync(fixture,'declared proof');const proof=await addDeclaredEvidence(fixture,{root,endpoint:origin,actorKind:'claude',actor:'Claude',type:'test'});assert.equal(proof.bytes,14);assert.match(proof.sha256,/^[a-f0-9]{64}$/);let observed=await recordObservation({kind:'cost.recorded',actor_kind:'codex',actor:'Codex',assertion:'measured_fact',summary:'Declared usage',payload:{amount:0.25,currency:'USD',known:true,total_tokens:100,cost_basis:'measured'}},{root,endpoint:origin});assert.equal(observed.duplicate,false);observed=await recordObservation({kind:'cost.recorded',actor_kind:'codex',actor:'Codex',assertion:'measured_fact',summary:'Declared usage',payload:{amount:0.25,currency:'USD',known:true,total_tokens:100,cost_basis:'measured'}},{root,endpoint:origin});assert.equal(observed.duplicate,true);await recordObservation({kind:'cost.recorded',actor_kind:'codex',actor:'Codex',assertion:'agent_statement',summary:'Estimated usage',payload:{model:'gpt-5.6-sol',input_tokens:1_000_000,output_tokens:0}},{root,endpoint:origin});const estimate=base().prepare("SELECT c.amount,c.known,e.payload FROM costs c JOIN events e ON e.id=c.event_id WHERE e.summary='Estimated usage'").get();assert.equal(estimate.amount,5);assert.equal(estimate.known,1);assert.equal(JSON.parse(estimate.payload).cost_basis,'estimated');state=setTracking(false,{root});assert.equal(state.enabled,false);assert.equal(trackingStatus(root).enabled,false);await assert.rejects(addDeclaredEvidence(fixture,{root,endpoint:origin}),/disabled/);await assert.rejects(recordObservation({kind:'event.recorded'},{root,endpoint:origin}),/disabled/);const response=await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'disabled-direct'},body:JSON.stringify({project:'cli-project',kind:'event.recorded',actor_kind:'codex',actor:'Codex',assertion:'agent_statement',summary:'Should be refused'})});assert.equal(response.status,409);setTracking(true,{root});assert.equal(trackingStatus(root).enabled,true)})
test('proof requires hash when available',async()=>{
  const body={project:'test',kind:'evidence.recorded',actor_kind:'codex',actor:'Codex',assertion:'measured_fact',summary:'Test output',payload:{label:'suite',type:'test',origin:'npm test',locator_kind:'path',path:'/tmp/out',status:'available'}}
  const response=await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'proof'},body:JSON.stringify(body)})
  assert.equal(response.status,400)
})
test('evidence verification reports verified, modified and missing files',async()=>{const fixture=join(dir,'proof.txt'),content='measured output';writeFileSync(fixture,content);const hash=createHash('sha256').update(content).digest('hex'),body={project:'test',kind:'evidence.recorded',actor_kind:'codex',actor:'Codex',assertion:'measured_fact',summary:'Verified file',payload:{label:'proof',type:'test',origin:'test',locator_kind:'path',path:fixture,status:'available',sha256:hash,bytes:content.length}};const created=await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'verified-proof'},body:JSON.stringify(body)}),uid=(await created.json()).events[0].event.id,proof=base().prepare('SELECT uid FROM evidence_manifests WHERE event_id=?').get(uid);let result=await(await fetch(`${origin}/api/evidence/${proof.uid}/verify`)).json();assert.equal(result.verification,'verified');writeFileSync(fixture,'changed');result=await(await fetch(`${origin}/api/evidence/${proof.uid}/verify`)).json();assert.equal(result.verification,'modified');rmSync(fixture);result=await(await fetch(`${origin}/api/evidence/${proof.uid}/verify`)).json();assert.equal(result.verification,'missing')})
test('exports round-trip without id collisions',()=>{ const bundle=exportObject(); const before=base().prepare('SELECT count(*) n FROM events').get().n; importBundle(bundle); assert.equal(base().prepare('SELECT count(*) n FROM events').get().n,before) })
test('machine journals are immutable deltas with content-addressed names',()=>{const machine=base().prepare('SELECT machine_id FROM events LIMIT 1').get().machine_id,bundle=exportJournal(machine,0),body=JSON.stringify(bundle),name=journalName(machine,bundle.cursor,body);assert.equal(bundle.scope,'machine-journal');assert.ok(bundle.tables.events.length);assert.match(name,/^orchestrator-journal--.+--\d{12}--[a-f0-9]{16}\.json$/);assert.equal(exportJournal(machine,bundle.cursor).tables.events.length,0);assert.equal(journalName(machine,bundle.cursor,body),name)})
test('cloud evidence index is content-addressed and deduplicated',()=>{const hash='a'.repeat(64),name=evidenceName(hash,'.PNG');assert.equal(name,`orchestrator-evidence--${hash}.png`);base().prepare("INSERT INTO evidence_cloud(provider,sha256,remote_id,remote_name,status) VALUES('gdrive',?,?,?,'available')").run(hash,'remote-1',name);base().prepare("INSERT INTO evidence_cloud(provider,sha256,remote_id,remote_name,status) VALUES('gdrive',?,?,?,'available') ON CONFLICT(provider,sha256) DO UPDATE SET remote_id=excluded.remote_id").run(hash,'remote-2',name);const rows=base().prepare("SELECT * FROM evidence_cloud WHERE provider='gdrive' AND sha256=?").all(hash);assert.equal(rows.length,1);assert.equal(rows[0].remote_id,'remote-2')})
test('pass protocol validates state and derives conflicts and stale bases',async()=>{
  const ingest=(key,kind,payload,summary=kind)=>fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':key},body:JSON.stringify({project:'test',kind,actor_kind:'codex',actor:'Codex',assertion:'system_record',summary,payload})})
  assert.equal((await ingest('bad-start','work.started',{session_id:'bad'})).status,400)
  assert.equal((await ingest('git-1','git.state',{machine:'mac-a',head_commit:'bbbbbbbb',branch:'main',dirty:false})).status,201)
  assert.equal((await ingest('start-a','work.started',{session_id:'pass-a',machine:'mac-a',base_commit:'aaaaaaaa',branch:'main',paths:['src/api']} ,'API pass')).status,201)
  assert.equal((await ingest('start-b','work.started',{session_id:'pass-b',machine:'mac-b',base_commit:'bbbbbbbb',branch:'main',paths:['src/api/routes.js']} ,'Routes pass')).status,201)
  let state=await (await fetch(`${origin}/api/projects/test/coordination`)).json()
  assert.equal(state.active.length,2);assert.equal(state.counts.stale,1);assert.equal(state.counts.conflicts,2);assert.deepEqual(state.active.find(row=>row.session_id==='pass-a').overlaps,['pass-b'])
  assert.equal((await ingest('finish-b','work.finished',{session_id:'pass-b',outcome:'completed'})).status,201)
  state=await (await fetch(`${origin}/api/projects/test/coordination`)).json();assert.equal(state.active.length,1);assert.equal(state.active[0].overlaps.length,0);assert.equal(state.recent.find(row=>row.session_id==='pass-b').status,'finished')
})
test('one derived-state rule prevents proven, blocker and judgment contradictions',async()=>{
  const objectiveUid=uid();base().prepare("INSERT INTO objectives(uid,project_id,title,status) VALUES(?,?,?,'in_progress')").run(objectiveUid,base().prepare("SELECT id FROM projects WHERE slug='test'").get().id,'Derived objective')
  const ingest=(key,kind,payload,status=201)=>fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':key},body:JSON.stringify({project:'test',objective:objectiveUid,kind,actor_kind:'human',actor:'tester',assertion:'human_judgment',summary:key,payload})}).then(response=>assert.equal(response.status,status))
  await ingest('state-block','blocker.opened',{title:'Needs review'});await ingest('state-request','human_judgment.requested',{});await ingest('state-proven','objective.updated',{status:'proven'})
  let detail=await(await fetch(`${origin}/api/projects/test`)).json(),objective=detail.objectives.find(row=>row.uid===objectiveUid)
  assert.equal(objective.status,'proven');assert.equal(detail.blockers.some(row=>row.objective_id===objective.id),false);assert.equal(detail.judgment_requests.some(row=>row.objective_id===objective.id),false)
  await ingest('state-reopen','objective.updated',{status:'in_progress'});detail=await(await fetch(`${origin}/api/projects/test`)).json();objective=detail.objectives.find(row=>row.uid===objectiveUid)
  assert.equal(objective.status,'in_progress');assert.equal(objective.reopened,true);assert.equal(detail.judgment_requests.some(row=>row.objective_id===objective.id),false)
  await ingest('state-new-request','human_judgment.requested',{});await ingest('state-new-blocker','blocker.opened',{title:'Blocked review',pass_ref:'42'});detail=await(await fetch(`${origin}/api/projects/test`)).json();assert.equal(detail.judgment_requests.some(row=>row.objective_id===objective.id),true);assert.equal(detail.blockers.find(row=>row.objective_id===objective.id).pass_ref,'42')
  const attention=await(await fetch(`${origin}/api/attention`)).json(),signals=attention.items.filter(row=>row.project.slug==='test');assert.equal(signals.some(row=>row.type==='judgment'&&row.objective.uid===objective.uid),true);assert.equal(signals.some(row=>row.type==='blocker'&&row.target.pass_ref==='42'),true);assert.equal(signals.some(row=>row.id.includes('state-old')),false)
})
test('portfolio aggregates tracked projects, machines and Git state',async()=>{const response=await fetch(`${origin}/api/portfolio`),portfolio=await response.json(),tracked=portfolio.projects.find(row=>row.slug==='test');assert.equal(response.status,200);assert.ok(tracked);assert.equal(tracked.git.branch,'main');assert.ok(tracked.machines.includes('mac-a'));assert.ok(Array.isArray(portfolio.detected));assert.ok(Array.isArray(portfolio.sync))})
test('analytics separates reported tokens and measured costs',async()=>{const body={project:'test',kind:'cost.recorded',actor_kind:'codex',actor:'Codex',assertion:'measured_fact',summary:'Reported API usage',payload:{amount:1.25,currency:'USD',known:true,category:'model',model:'gpt-test',input_tokens:1200,output_tokens:300,cached_tokens:400,total_tokens:1500,cost_basis:'measured',duration_ms:900,requests:2}},ingested=await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'analytics-usage'},body:JSON.stringify(body)});assert.equal(ingested.status,201);const response=await fetch(`${origin}/api/analytics?project=test&days=30`),data=await response.json();assert.equal(response.status,200);assert.equal(data.totals.total_tokens,1500);assert.equal(data.totals.input_tokens,1200);assert.equal(data.totals.cached_tokens,400);assert.equal(data.totals.measured_cost,1.25);assert.equal(data.models.find(row=>row.key==='gpt-test').tokens,1500)})
test('resume reports only changes after the supplied visit time',async()=>{let response=await fetch(`${origin}/api/projects/test/resume?since=${encodeURIComponent('2000-01-01T00:00:00Z')}`),data=await response.json();assert.equal(response.status,200);assert.ok(data.summary.events>0);assert.ok(data.changed_objectives.length>0);response=await fetch(`${origin}/api/projects/test/resume?since=${encodeURIComponent('2999-01-01T00:00:00Z')}`);data=await response.json();assert.equal(data.summary.events,0);assert.deepEqual(data.recent,[])})
test('global briefing groups recent changes by active project',async()=>{let response=await fetch(`${origin}/api/briefing?since=${encodeURIComponent('2000-01-01T00:00:00Z')}`),data=await response.json();assert.equal(response.status,200);assert.ok(data.summary.events>0);assert.equal(data.projects.some(row=>row.slug==='test'&&row.events>0),true);assert.equal(data.recent.every(row=>row.project&&row.target),true);response=await fetch(`${origin}/api/briefing?since=${encodeURIComponent('2999-01-01T00:00:00Z')}`);data=await response.json();assert.equal(data.summary.events,0)})
test('briefing exports preserve the selected period',async()=>{const since='2000-01-01T00:00:00.000Z';let response=await fetch(`${origin}/api/briefing/export/json?since=${encodeURIComponent(since)}`),data=await response.json();assert.equal(response.status,200);assert.equal(data.format,'orchestrator-briefing');assert.equal(data.since,since);assert.match(response.headers.get('content-disposition'),/\.json/);response=await fetch(`${origin}/api/briefing/export/markdown?since=${encodeURIComponent(since)}`);const markdown=await response.text();assert.equal(response.status,200);assert.match(markdown,/^# Orchestrator recent briefing/);assert.match(markdown,/## Recent activity/)})
test('confidence is bounded and explains every penalty',async()=>{const response=await fetch(`${origin}/api/projects/test/confidence`),data=await response.json();assert.equal(response.status,200);assert.ok(data.score>=0&&data.score<=100);assert.ok(['high','medium','low'].includes(data.label));assert.deepEqual(Object.keys(data.components),['evidence','blockers','judgments','coordination','git','freshness']);assert.equal(data.score,Math.max(0,100-Object.values(data.penalties).reduce((sum,value)=>sum+value,0)))})
test('AI workspace exposes 41 passive professional capabilities and portable handoff',async()=>{const response=await fetch(`${origin}/api/projects/test/ai-workspace`),data=await response.json(),ids=new Set(data.features.map(row=>row.id));assert.equal(response.status,200);assert.equal(data.format,'orchestrator-ai-workspace');assert.equal(data.features.length,41);assert.equal(ids.size,41);for(const id of ['next_work','git_guard','architecture_decisions','dependency_radar','test_coverage_map','regression_watchlist','evidence_diff','commit_traceability','requirement_coverage','assumption_register','technical_debt','security_center','performance_baseline','environment_matrix','ownership_map','review_coverage','verification_policy','knowledge_gaps','release_narrative','incident_timeline','project_template','portfolio_intelligence'])assert.ok(ids.has(id),id);assert.ok(data.next.title);assert.equal(data.summary.features,41);let handoff=await fetch(`${origin}/api/projects/test/handoff.md`),markdown=await handoff.text();assert.equal(handoff.status,200);assert.match(markdown,/AI handoff/);assert.match(markdown,/Orchestrator is observation-only/);handoff=await fetch(`${origin}/api/projects/test/handoff.json`);assert.equal(handoff.status,200);assert.equal((await handoff.json()).project,'Test')})
test('universal search returns typed contextual links',async()=>{let response=await fetch(`${origin}/api/search?q=${encodeURIComponent('Observed state')}`),data=await response.json();assert.equal(response.status,200);assert.equal(data.results.some(row=>row.type==='event'&&row.project.slug==='test'),true);response=await fetch(`${origin}/api/search?q=${encodeURIComponent('proof')}`);data=await response.json();assert.equal(data.results.some(row=>row.type==='evidence'&&row.target.view==='evidence'),true);response=await fetch(`${origin}/api/search?q=x`);data=await response.json();assert.deepEqual(data.results,[])})
test('snapshots are stable, portable and comparable',async()=>{const first=await(await fetch(`${origin}/api/projects/test/snapshot`)).json(),same=await(await fetch(`${origin}/api/projects/test/snapshot`)).json();assert.equal(first.format,'orchestrator-snapshot');assert.equal(first.state_hash,same.state_hash);const body={project:'test',kind:'event.recorded',actor_kind:'human',actor:'reviewer',assertion:'human_judgment',summary:'Snapshot boundary'};await fetch(`${origin}/api/ingest`,{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':'snapshot-boundary'},body:JSON.stringify(body)});const afterSnapshot=await(await fetch(`${origin}/api/projects/test/snapshot`)).json();assert.notEqual(first.state_hash,afterSnapshot.state_hash);const response=await fetch(`${origin}/api/snapshots/compare`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({before:first,after:afterSnapshot})}),diff=await response.json();assert.equal(response.status,200);assert.equal(diff.identical,false);assert.equal(diff.project.uid,project.uid)})
test('planning suggestions require review and ClickUp credentials stay redacted',async()=>{let response=await fetch(`${origin}/api/projects/test/planning/generate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({need:'Add a documented recovery workflow.'})}),data=await response.json();assert.equal(response.status,200);assert.equal(data.execution,false);assert.ok(data.proposals.some(row=>row.status==='proposed'));assert.equal(data.proposals.some(row=>row.source_kind==='human'&&row.title==='Add a documented recovery workflow'),true);const proposal=data.proposals.find(row=>row.status==='proposed');response=await fetch(`${origin}/api/projects/test/planning/${proposal.uid}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:'approved',reviewer:'test reviewer'})});assert.equal(response.status,200);assert.equal((await response.json()).status,'approved');response=await fetch(`${origin}/api/projects/test/clickup`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({workspace_id:'team-1',list_id:'list-1',tag_name:'test-project',token:'secret-token',enabled:true})});data=await response.json();assert.equal(response.status,200);assert.equal(data.token,'configured');assert.equal(data.tag_name,'test-project');assert.deepEqual(data.progress.statuses,[]);response=await fetch(`${origin}/api/projects/test/planning`);data=await response.json();assert.equal(data.execution,false);assert.equal(data.clickup.token,'configured')})
test('published runtime has no execution primitive',()=>{ for(const file of ['src/server.js','src/cli.js','src/tracking.js','src/intelligence.js','src/planning.js','src/db/index.js','src/db/migrate.js']) assert.doesNotMatch(readFileSync(new URL(`../${file}`,import.meta.url),'utf8'),/node:child_process|\bspawn\s*\(|\bexecFile|\bkill\s*\(|\/claim\b/) })
test('ClickUp sync progress is passive and initially ready',async()=>{const response=await fetch(`${origin}/api/projects/test/clickup/progress`),data=await response.json();assert.equal(response.status,200);assert.deepEqual(data,{active:false,percent:0,message:'Ready'})})
test('API exposes no execution routes',()=>{ const routes=[]; for(const layer of createServer()._router.stack){ if(layer.name!=='router') continue; for(const child of layer.handle.stack) if(child.route) routes.push(`${Object.keys(child.route.methods)[0]} ${child.route.path}`) } assert.equal(routes.some((route)=>/run|claim|cancel|chore|worker|agent|unity|browser/i.test(route)),false) })
