import { base, json, nowStamp } from './index.js'

const comparable=row=>JSON.stringify({title:row.title,intent:row.intent??null,success_criteria:row.success_criteria??null,status:row.status,priority:row.priority})
function recordConflict(db,bundle,row,local,provider){
  const incoming=comparable(row),existing=comparable(local);if(incoming===existing)return
  const key=`objective:${row.uid}:${Buffer.from(existing+incoming).toString('base64url').slice(0,80)}`
  db.prepare(`INSERT OR IGNORE INTO sync_conflicts(uid,provider,entity_type,entity_uid,local_value,incoming_value,incoming_machine_id,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(key,provider||null,'objective',row.uid,existing,incoming,bundle.machine_id||null,nowStamp())
}

export function importBundle(bundle,{provider=null}={}) {
  if (bundle?.format !== 'orchestrator-memory' || bundle?.version !== 1 || !bundle.tables) throw new Error('Unsupported import format.')
  const inserted = {}
  base().transaction(() => {
    const projectMap = new Map(); const chapterMap = new Map(); const objectiveMap = new Map(); const eventMap = new Map(); const workspaceMap=new Map();const memberMap=new Map()
    for(const row of bundle.tables.workspaces||[]){base().prepare('INSERT INTO workspaces(uid,name,status,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(uid) DO NOTHING').run(row.uid,row.name,row.status,row.created_at,row.updated_at);workspaceMap.set(row.id,base().prepare('SELECT id FROM workspaces WHERE uid=?').get(row.uid).id)}
    for (const row of bundle.tables.projects || []) { base().prepare('INSERT INTO projects(uid,slug,name,description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(uid) DO NOTHING').run(row.uid,row.slug,row.name,row.description,row.status,row.created_at,row.updated_at); projectMap.set(row.id,base().prepare('SELECT id FROM projects WHERE uid=?').get(row.uid).id) }
    for(const row of bundle.tables.workspace_projects||[]){const workspace=workspaceMap.get(row.workspace_id),project=projectMap.get(row.project_id);if(workspace&&project)base().prepare('INSERT OR IGNORE INTO workspace_projects(workspace_id,project_id,created_at) VALUES(?,?,?)').run(workspace,project,row.created_at||nowStamp())}
    for(const row of bundle.tables.workspace_members||[]){const workspace=workspaceMap.get(row.workspace_id);if(!workspace)continue;base().prepare('INSERT INTO workspace_members(uid,workspace_id,display_name,email,status,external_ids,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(uid) DO NOTHING').run(row.uid,workspace,row.display_name,row.email,row.status,row.external_ids,row.created_at,row.updated_at);memberMap.set(row.id,base().prepare('SELECT id FROM workspace_members WHERE uid=?').get(row.uid).id)}
    for(const row of bundle.tables.workspace_machines||[]){const workspace=workspaceMap.get(row.workspace_id);if(!workspace)continue;base().prepare('INSERT INTO workspace_machines(uid,workspace_id,member_id,machine_key,label,platform,last_seen_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,machine_key) DO UPDATE SET member_id=COALESCE(excluded.member_id,workspace_machines.member_id),last_seen_at=MAX(excluded.last_seen_at,workspace_machines.last_seen_at),updated_at=excluded.updated_at').run(row.uid,workspace,memberMap.get(row.member_id)||null,row.machine_key,row.label,row.platform,row.last_seen_at,row.created_at,row.updated_at)}
    for(const row of bundle.tables.chapters||[]){const p=projectMap.get(row.project_id);if(!p)continue;base().prepare('INSERT INTO chapters(uid,project_id,title,position,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(uid) DO NOTHING').run(row.uid,p,row.title,row.position,row.status,row.created_at,row.updated_at);chapterMap.set(row.id,base().prepare('SELECT id FROM chapters WHERE uid=?').get(row.uid).id)}
    for (const row of bundle.tables.objectives || []) { const p=projectMap.get(row.project_id); if(!p) continue;const local=base().prepare('SELECT * FROM objectives WHERE uid=?').get(row.uid);if(local)recordConflict(base(),bundle,row,local,provider);base().prepare('INSERT INTO objectives(uid,project_id,chapter_id,parent_id,title,intent,success_criteria,status,priority,due_at,estimate_minutes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uid) DO NOTHING').run(row.uid,p,chapterMap.get(row.chapter_id)||null,null,row.title,row.intent,row.success_criteria,row.status,row.priority,row.due_at||null,row.estimate_minutes??null,row.created_at,row.updated_at); objectiveMap.set(row.id,base().prepare('SELECT id FROM objectives WHERE uid=?').get(row.uid).id) }
    for(const row of bundle.tables.objectives||[]){if(!row.parent_id)continue;const id=objectiveMap.get(row.id),parent=objectiveMap.get(row.parent_id);if(id&&parent)base().prepare('UPDATE objectives SET parent_id=? WHERE id=? AND parent_id IS NULL').run(parent,id)}
    inserted.objective_dependencies=0
    for(const row of bundle.tables.objective_dependencies||[]){const p=projectMap.get(row.project_id),objective=objectiveMap.get(row.objective_id),dependsOn=objectiveMap.get(row.depends_on_id);if(!p||!objective||!dependsOn)continue;inserted.objective_dependencies+=base().prepare('INSERT OR IGNORE INTO objective_dependencies(project_id,objective_id,depends_on_id,created_at) VALUES(?,?,?,?)').run(p,objective,dependsOn,row.created_at||nowStamp()).changes}
    for (const row of bundle.tables.events || []) { const p=projectMap.get(row.project_id); if(!p) continue; base().prepare('INSERT INTO events(uid,project_id,objective_id,kind,actor_kind,actor,assertion,summary,payload,occurred_at,recorded_at,idempotency_key,source,machine_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uid) DO NOTHING').run(row.uid,p,objectiveMap.get(row.objective_id)||null,row.kind,row.actor_kind,row.actor,row.assertion,row.summary,json.write(row.payload),row.occurred_at,row.recorded_at,`import:${row.uid}`,row.source,row.machine_id||bundle.machine_id||null); eventMap.set(row.id,base().prepare('SELECT id FROM events WHERE uid=?').get(row.uid).id) }
    const simple = ['evidence_manifests','decisions','blockers','verdicts','costs','cleanups']
    for (const table of simple) { inserted[table]=0; for(const row of bundle.tables[table]||[]){ const p=projectMap.get(row.project_id),e=eventMap.get(row.event_id); if(!p||!e) continue; const copy={...row,project_id:p,event_id:e,objective_id:objectiveMap.get(row.objective_id)||null}; delete copy.id; const fields=Object.keys(copy); const result=base().prepare(`INSERT INTO ${table}(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')}) ON CONFLICT(uid) DO NOTHING`).run(...fields.map((field)=>copy[field])); inserted[table]+=result.changes } }
    inserted.work_proposals=0
    const proposalMap=new Map()
    for(const row of bundle.tables.work_proposals||[]){const p=projectMap.get(row.project_id);if(!p)continue;const copy={...row,project_id:p,objective_id:objectiveMap.get(row.objective_id)||null};delete copy.id;const fields=Object.keys(copy),result=base().prepare(`INSERT INTO work_proposals(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')}) ON CONFLICT(fingerprint) DO NOTHING`).run(...fields.map(field=>copy[field]));inserted.work_proposals+=result.changes;proposalMap.set(row.id,base().prepare('SELECT id FROM work_proposals WHERE fingerprint=?').get(row.fingerprint).id)}
    inserted.clickup_ticket_links=0
    for(const row of bundle.tables.clickup_ticket_links||[]){const p=projectMap.get(row.project_id);if(!p)continue;const copy={...row,project_id:p,proposal_id:proposalMap.get(row.proposal_id)||null,objective_id:objectiveMap.get(row.objective_id)||null};delete copy.id;const fields=Object.keys(copy),result=base().prepare(`INSERT INTO clickup_ticket_links(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')}) ON CONFLICT(fingerprint) DO NOTHING`).run(...fields.map(field=>copy[field]));inserted.clickup_ticket_links+=result.changes}
    inserted.project_members=0;for(const row of bundle.tables.project_members||[]){const project=projectMap.get(row.project_id),member=memberMap.get(row.member_id);if(project&&member)inserted.project_members+=base().prepare('INSERT OR IGNORE INTO project_members(project_id,member_id,role,created_at) VALUES(?,?,?,?)').run(project,member,row.role,row.created_at||nowStamp()).changes}
    inserted.external_items=0;for(const row of bundle.tables.external_items||[]){const project=projectMap.get(row.project_id);if(!project)continue;const copy={...row,project_id:project,chapter_id:chapterMap.get(row.chapter_id)||null,objective_id:objectiveMap.get(row.objective_id)||null,assignee_member_id:memberMap.get(row.assignee_member_id)||null};delete copy.id;const fields=Object.keys(copy),result=base().prepare(`INSERT INTO external_items(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')}) ON CONFLICT(provider,external_id) DO UPDATE SET status=excluded.status,title=excluded.title,url=excluded.url,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at`).run(...fields.map(field=>copy[field]));inserted.external_items+=result.changes}
    inserted.knowledge_rules=0;for(const row of bundle.tables.knowledge_rules||[]){const copy={...row};delete copy.id;const fields=Object.keys(copy),result=base().prepare(`INSERT INTO knowledge_rules(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')}) ON CONFLICT(fingerprint) DO UPDATE SET title=excluded.title,problem=excluded.problem,recommendation=excluded.recommendation,avoid_text=excluded.avoid_text,tags=excluded.tags,project_slugs=excluded.project_slugs,source_events=excluded.source_events,confidence=excluded.confidence,occurrences=excluded.occurrences,status=excluded.status,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at`).run(...fields.map(field=>copy[field]));inserted.knowledge_rules+=result.changes}
    inserted.project_specifications=0;for(const row of bundle.tables.project_specifications||[]){const project=projectMap.get(row.project_id);if(!project)continue;const copy={...row,project_id:project};delete copy.id;const fields=Object.keys(copy),result=base().prepare(`INSERT INTO project_specifications(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')}) ON CONFLICT(project_id) DO UPDATE SET revision=MAX(project_specifications.revision,excluded.revision),title=CASE WHEN excluded.revision>=project_specifications.revision THEN excluded.title ELSE project_specifications.title END,content=CASE WHEN excluded.revision>=project_specifications.revision THEN excluded.content ELSE project_specifications.content END,updated_at=MAX(project_specifications.updated_at,excluded.updated_at)`).run(...fields.map(field=>copy[field]));inserted.project_specifications+=result.changes}
    inserted.projects=projectMap.size; inserted.objectives=objectiveMap.size; inserted.events=eventMap.size
  })()
  return { imported: inserted }
}
