import { execFileSync } from 'node:child_process'
import { closeSync, existsSync, openSync, readFileSync, readSync, readdirSync, statSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { base, json, nowStamp } from './db/index.js'

const providers=['codex','claude','gemini','opencode','copilot']
const periods=['daily','weekly','monthly']
const settingsKey='ai-usage-policy'
const limitsKey='ai-provider-limits'
const startOf=(period,date=new Date())=>{const value=new Date(date);if(period==='daily')value.setHours(0,0,0,0);if(period==='weekly'){const day=(value.getDay()+6)%7;value.setDate(value.getDate()-day);value.setHours(0,0,0,0)}if(period==='monthly'){value.setDate(1);value.setHours(0,0,0,0)}return value.toISOString()}
const readTail=(path,max=2*1024*1024)=>{const stat=statSync(path),length=Math.min(stat.size,max),fd=openSync(path,'r'),buffer=Buffer.alloc(length);readSync(fd,buffer,0,length,stat.size-length);closeSync(fd);return buffer.toString('utf8')}
const recentJsonl=(root,limit=120)=>{if(!existsSync(root))return[];const files=[],walk=directory=>{for(const entry of readdirSync(directory,{withFileTypes:true})){const path=join(directory,entry.name);if(entry.isDirectory())walk(path);else if(entry.isFile()&&entry.name.endsWith('.jsonl')){const stat=statSync(path);files.push({path,mtime:stat.mtimeMs})}}};walk(root);return files.sort((a,b)=>b.mtime-a.mtime).slice(0,limit)}
const storedLimits=()=>json.read(base().prepare('SELECT value FROM management_settings WHERE key=?').get(limitsKey)?.value,{providers:{},updated_at:null})
const persistLimits=value=>base().prepare("INSERT INTO management_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(limitsKey,json.write(value),nowStamp())
const resetIso=value=>value?new Date(Number(value)*1000).toISOString():null
const reached=quota=>Boolean(quota&&((Number(quota.used_percent??quota.utilization)||0)>=100||quota.reached))

export function aiUsageSettings(){const stored=json.read(base().prepare('SELECT value FROM management_settings WHERE key=?').get(settingsKey)?.value,{});return{auto_switch:Boolean(stored.auto_switch)}}
export function saveAiUsageSettings(input={}){const settings={auto_switch:Boolean(input.auto_switch)};base().prepare("INSERT INTO management_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(settingsKey,json.write(settings),nowStamp());return settings}

function readCodexLimits(){const latest=new Map();for(const file of recentJsonl(join(homedir(),'.codex','sessions'))){let lines;try{lines=readTail(file.path).split('\n')}catch{continue}for(let index=lines.length-1;index>=0;index--){let row;try{row=JSON.parse(lines[index])}catch{continue}const rate=row?.payload?.type==='token_count'?row.payload.rate_limits:null;if(!rate)continue;const observedAt=row.timestamp||new Date(file.mtime).toISOString(),windows=[['primary',rate.primary],['secondary',rate.secondary]];for(const [kind,window] of windows){if(!window)continue;const id=`${rate.limit_id||'codex'}:${kind}`,quota={id,kind,group:window.window_minutes>=10000?'hebdomadaire':window.window_minutes>=1440?'quotidienne':'session',label:rate.limit_name||'Codex',used_percent:Number(window.used_percent)||0,window_minutes:Number(window.window_minutes)||null,resets_at:resetIso(window.resets_at),plan_type:rate.plan_type||null,reached:Boolean(rate.rate_limit_reached_type)||Number(window.used_percent)>=100,observed_at:observedAt};if(!latest.has(id)||Date.parse(observedAt)>Date.parse(latest.get(id).observed_at))latest.set(id,quota)}}}const quotas=[...latest.values()].sort((a,b)=>(a.window_minutes||0)-(b.window_minutes||0));return{provider:'codex',available:Boolean(quotas.length),source:'Limites annoncées par Codex',freshness:quotas[0]?.observed_at||null,quotas,exhausted:quotas.some(reached),error:quotas.length?null:'Aucune limite récente exposée par Codex.'}}

async function readClaudeLimits(){try{const credentials=JSON.parse(execFileSync('security',['find-generic-password','-s','Claude Code-credentials','-w'],{encoding:'utf8',timeout:3000,maxBuffer:1024*1024})),token=credentials?.claudeAiOauth?.accessToken;if(!token)throw new Error('Session OAuth Claude introuvable.');const response=await fetch('https://api.anthropic.com/api/oauth/usage',{headers:{authorization:`Bearer ${token}`,'anthropic-beta':'oauth-2025-04-20','user-agent':'orchestrator-local'},signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`Claude usage HTTP ${response.status}`);const value=await response.json(),names={session:'Session en cours',weekly_all:'Hebdomadaire',weekly_scoped:'Hebdomadaire ciblée'},quotas=(value.limits||[]).map((item,index)=>({id:`claude:${item.kind||index}`,kind:item.kind||'usage',group:item.group==='weekly'?'hebdomadaire':item.group||'usage',label:item.scope?.model?.display_name?`${names[item.kind]||item.group} · ${item.scope.model.display_name}`:names[item.kind]||item.group||item.kind||'Claude',used_percent:Number(item.percent)||0,resets_at:item.resets_at||null,reached:Number(item.percent)>=100||item.severity==='exhausted',severity:item.severity||'normal',active:Boolean(item.is_active)})),extra=value.extra_usage?{enabled:Boolean(value.extra_usage.is_enabled),monthly_limit:value.extra_usage.monthly_limit,used_credits:value.extra_usage.used_credits,utilization:value.extra_usage.utilization,spend_limit_reached:Boolean(value.extra_usage.spend_limit_reached)}:null;return{provider:'claude',available:true,source:'Limites annoncées par Claude',freshness:nowStamp(),quotas,extra_usage:extra,exhausted:quotas.some(reached)||Boolean(extra?.spend_limit_reached),error:null}}catch(error){return{provider:'claude',available:false,source:'Limites annoncées par Claude',freshness:null,quotas:[],extra_usage:null,exhausted:false,error:error instanceof Error?error.message:String(error)}}}

export async function refreshProviderLimits(){const previous=storedLimits(),codex=readCodexLimits(),claude=await readClaudeLimits(),value={providers:{codex,claude},updated_at:nowStamp()};if(!claude.available&&previous.providers?.claude?.available)value.providers.claude={...previous.providers.claude,error:claude.error,stale:true};persistLimits(value);return value}

const sessionRows=()=>base().prepare('SELECT uid,provider,status,created_at,metadata FROM terminal_sessions ORDER BY created_at DESC').all().map(row=>({...row,metadata:json.read(row.metadata,{})}))
const configuredDefaults=()=>{const result={codex:{model:null,effort:'medium'},claude:{model:null,effort:'high'},gemini:{model:null,effort:''},opencode:{model:null,effort:''},copilot:{model:null,effort:''}};try{const value=readFileSync(join(homedir(),'.codex','config.toml'),'utf8');result.codex.model=value.match(/^model\s*=\s*["']([^"']+)["']/m)?.[1]||null;result.codex.effort=value.match(/^model_reasoning_effort\s*=\s*["']([^"']+)["']/m)?.[1]||result.codex.effort}catch{}try{const value=JSON.parse(readFileSync(join(homedir(),'.claude','settings.json'),'utf8'));result.claude.model=typeof value.model==='string'?value.model:null;result.claude.effort=typeof value.effort==='string'?value.effort:result.claude.effort}catch{}return result}
const modelOf=(row,defaults)=>String(row.metadata?.resolved_model||row.metadata?.launch_options?.model||row.metadata?.model||defaults[row.provider]?.model||'Modèle non communiqué')
const effortOf=(row,defaults)=>String(row.metadata?.resolved_effort||row.metadata?.launch_options?.effort||defaults[row.provider]?.effort||'')
const countSince=(rows,provider,period)=>rows.filter(row=>row.provider===provider&&row.created_at>=startOf(period)).length

export async function aiUsageDashboard({refresh=true}={}){const rows=sessionRows(),defaults=configuredDefaults(),settings=aiUsageSettings(),providerLimits=refresh?await refreshProviderLimits():storedLimits(),counts={},models=new Map();for(const provider of providers){counts[provider]={};for(const period of periods)counts[provider][period]={used:countSince(rows,provider,period)}}for(const row of rows){const model=modelOf(row,defaults),effort=effortOf(row,defaults),id=`${row.provider}:${model}:${effort}`,item=models.get(id)||{provider:row.provider,model,effort,sessions:0,last_used_at:null};item.sessions++;if(!item.last_used_at)item.last_used_at=row.created_at;models.set(id,item)}const totals={};for(const period of periods)totals[period]=providers.reduce((sum,provider)=>sum+counts[provider][period].used,0);const lastSwitch=rows.find(row=>row.metadata?.provider_switched_from);return{generated_at:nowStamp(),settings,provider_limits:providerLimits.providers||{},limits_updated_at:providerLimits.updated_at||null,counts,totals,total_sessions:rows.length,active_sessions:rows.filter(row=>['starting','running'].includes(row.status)).length,models:[...models.values()].sort((a,b)=>b.sessions-a.sessions).slice(0,30),last_switch:lastSwitch?{session_uid:lastSwitch.uid,requested:lastSwitch.metadata.provider_switched_from,provider:lastSwitch.provider,reason:lastSwitch.metadata.provider_switch_reason,created_at:lastSwitch.created_at}:null,provenance:{sessions:'Sessions lancées et sauvegardées par Orchestrator.',quotas:'Limites lues depuis les données exposées par chaque CLI. Une valeur absente reste inconnue.'}}}

export function routeAiProvider(requested,{available=()=>true}={}){const provider=providers.includes(requested)?requested:'codex',settings=aiUsageSettings(),stored=storedLimits(),limits=provider==='codex'?readCodexLimits():stored.providers?.[provider];if(!settings.auto_switch||!limits?.exhausted)return{provider,requested,switched:false,reason:null};const alternate=providers.find(item=>item!==provider&&available(item)&&!stored.providers?.[item]?.exhausted);return alternate?{provider:alternate,requested,switched:true,reason:`Quota réel ${provider} atteint.`}:{provider,requested,switched:false,reason:`Quota ${provider} atteint, aucune IA de secours disponible.`}}
