import { base, json, nowStamp } from './db/index.js'
import { deriveConfidence, deriveCoordination, deriveProjectState } from './state.js'

const ageHours=value=>value?Math.max(0,(Date.now()-new Date(value).getTime())/3600000):Infinity
const compact=row=>({uid:row.uid,kind:row.kind,summary:row.summary,actor:row.actor,assertion:row.assertion,occurred_at:row.occurred_at,objective_uid:row.objective_uid||null,objective_title:row.objective_title||null,payload:row.payload})
const feature=(id,title,status,summary,items=[],metric=null)=>({id,title,status,summary,metric,items:items.slice(0,12)})

export function deriveAiWorkspace(project){
  const db=base(),state=deriveProjectState(project.id),coordination=deriveCoordination(project.id),confidence=deriveConfidence(project.id)
  const events=db.prepare(`SELECT e.*,o.uid objective_uid,o.title objective_title FROM events e LEFT JOIN objectives o ON o.id=e.objective_id WHERE e.project_id=? ORDER BY e.occurred_at DESC,e.id DESC`).all(project.id).map(row=>({...row,payload:json.read(row.payload,{})}))
  const evidence=db.prepare(`SELECT m.*,o.uid objective_uid,o.title objective_title,e.occurred_at event_at FROM evidence_manifests m JOIN events e ON e.id=m.event_id LEFT JOIN objectives o ON o.id=m.objective_id WHERE m.project_id=? ORDER BY m.created_at DESC,m.id DESC`).all(project.id)
  const decisions=db.prepare(`SELECT d.*,o.uid objective_uid,o.title objective_title FROM decisions d LEFT JOIN objectives o ON o.id=d.objective_id WHERE d.project_id=? ORDER BY d.created_at DESC,d.id DESC`).all(project.id)
  const verdicts=db.prepare(`SELECT v.*,e.actor,e.payload,o.uid objective_uid,o.title objective_title FROM verdicts v JOIN events e ON e.id=v.event_id LEFT JOIN objectives o ON o.id=v.objective_id WHERE v.project_id=? ORDER BY v.created_at DESC,v.id DESC`).all(project.id).map(row=>({...row,payload:json.read(row.payload,{})}))
  const costs=db.prepare(`SELECT c.*,e.actor,e.actor_kind,e.payload,o.uid objective_uid,o.title objective_title FROM costs c JOIN events e ON e.id=c.event_id LEFT JOIN objectives o ON o.id=c.objective_id WHERE c.project_id=? ORDER BY c.created_at DESC,c.id DESC`).all(project.id).map(row=>({...row,payload:json.read(row.payload,{})}))
  const activeObjectives=state.objectives.filter(row=>!['proven','abandoned'].includes(row.status)),latest=events[0]||null,latestGit=coordination.latest_git
  const failures=events.filter(row=>row.kind==='verdict.recorded'&&['fail','inconclusive'].includes(row.payload.verdict)||row.kind==='work.finished'&&row.payload.outcome==='failed')
  const groupedFailures=[...failures.reduce((map,row)=>{const key=row.objective_uid||row.summary.toLowerCase().replace(/\d+/g,'#'),item=map.get(key)||{key,title:row.objective_title||row.summary,count:0,last_at:row.occurred_at,attempts:[]};item.count++;item.attempts.push(row.summary);if(row.occurred_at>item.last_at)item.last_at=row.occurred_at;map.set(key,item);return map},new Map()).values()].sort((a,b)=>b.count-a.count)
  const evidenceDebt=evidence.filter(row=>row.status!=='available'||!row.sha256),expired=evidence.filter(row=>{const objective=state.objectives.find(item=>item.id===row.objective_id);return objective?.last_activity&&new Date(objective.last_activity)>new Date(row.created_at)&&ageHours(row.created_at)>24})
  const decisionQueue=state.judgmentRequests.map(request=>{const objective=state.objectives.find(row=>row.id===request.objective_id);return{uid:request.uid,title:request.summary,objective_uid:objective?.uid||null,objective_title:objective?.title||null,requested_at:request.occurred_at,age_hours:Math.round(ageHours(request.occurred_at)),impact:objective?.priority<=25?'high':'normal'}})
  const agentRows=[...costs.reduce((map,row)=>{const key=row.actor||row.actor_kind||'unknown',item=map.get(key)||{agent:key,cost:0,tokens:0,records:0,proven:0,failures:0};item.records++;if(row.known&&row.amount!=null)item.cost+=row.amount;item.tokens+=Number(row.payload.total_tokens||Number(row.payload.input_tokens||0)+Number(row.payload.output_tokens||0));map.set(key,item);return map},new Map()).values()]
  for(const row of verdicts){const item=agentRows.find(agent=>agent.agent===row.actor)||agentRows[0];if(item){if(row.verdict==='pass')item.proven++;if(row.verdict==='fail')item.failures++}}
  const prompts=events.filter(row=>row.payload.prompt||row.payload.prompt_version||row.kind==='prompt.recorded').map(row=>({summary:row.summary,prompt:row.payload.prompt||null,version:row.payload.prompt_version||'unversioned',actor:row.actor,occurred_at:row.occurred_at}))
  const gitRows=events.filter(row=>row.kind==='git.state').map(row=>({machine:row.payload.machine||row.machine_id,branch:row.payload.branch,head_commit:row.payload.head_commit,dirty:Boolean(row.payload.dirty),occurred_at:row.occurred_at}))
  const branches=[...new Map(gitRows.map(row=>[row.branch,row])).values()]
  const risks=[...state.blockers.map(row=>({type:'blocker',title:row.title,detail:row.detail,probability:'certain',impact:'high'})),...evidenceDebt.map(row=>({type:'evidence',title:row.label,detail:row.status,probability:'high',impact:'medium'})),...coordination.active.filter(row=>row.stale||row.overlaps.length).map(row=>({type:'coordination',title:row.session_id,detail:row.stale?'Stale Git base':`Overlaps ${row.overlaps.join(', ')}`,probability:'high',impact:'high'}))]
  const duplicates=[...events.reduce((map,row)=>{const key=row.summary.trim().toLowerCase(),item=map.get(key)||{summary:row.summary,count:0};item.count++;map.set(key,item);return map},new Map()).values()].filter(row=>row.count>1).sort((a,b)=>b.count-a.count)
  const contradictions=state.objectives.filter(row=>row.status==='proven'&&(row.open_blocker_count||row.judgment_requested)).map(row=>({title:row.title,detail:'Proven state conflicts with unresolved attention'}))
  const doneContracts=state.objectives.map(row=>{const criteria=String(row.success_criteria||'').split(/\n|;/).map(value=>value.trim()).filter(Boolean),proofs=evidence.filter(proof=>proof.objective_id===row.id&&proof.status==='available'&&proof.sha256).length,passes=verdicts.filter(verdict=>verdict.objective_id===row.id&&verdict.verdict==='pass').length;return{uid:row.uid,title:row.title,status:row.status,criteria:criteria.length,proofs,passing_verdicts:passes,ready:criteria.length>0&&proofs>0&&passes>0}})
  const releaseChecks=[{name:'All objectives terminal',pass:activeObjectives.length===0},{name:'No open blockers',pass:state.blockers.length===0},{name:'No pending human judgment',pass:decisionQueue.length===0},{name:'Evidence available and hashed',pass:evidenceDebt.length===0},{name:'Git state reported and clean',pass:Boolean(latestGit&&!latestGit.dirty)},{name:'No active pass conflict',pass:coordination.counts.conflicts===0}]
  const architectureDecisions=decisions.map(row=>({title:row.title,status:row.status,objective_title:row.objective_title,body:row.body,created_at:row.created_at}))
  const dependencySignals=events.filter(row=>row.payload.dependencies||row.payload.dependency||/dependency|package|npm audit|composer audit/i.test(row.summary)).map(row=>({title:row.summary,detail:row.payload.dependency||row.payload.dependencies||row.payload.version||'Dependency observation',occurred_at:row.occurred_at}))
  const testCoverage=state.objectives.map(row=>{const proofs=evidence.filter(item=>item.objective_id===row.id&&/test|report|coverage|playwright|unit|integration/i.test(`${item.type} ${item.origin} ${item.label}`));return{uid:row.uid,title:row.title,status:row.status,tests:proofs.length,covered:proofs.length>0}})
  const regressionWatch=state.objectives.filter(row=>row.reopened||verdicts.some(item=>item.objective_id===row.id&&item.verdict==='fail')).map(row=>({uid:row.uid,title:row.title,reopened:row.reopened,failures:verdicts.filter(item=>item.objective_id===row.id&&item.verdict==='fail').length,last_activity:row.last_activity}))
  const evidenceDiffs=[...evidence.reduce((map,row)=>{const key=`${row.objective_id||'project'}:${row.type}`,item=map.get(key)||{title:row.objective_title||row.type,type:row.type,versions:0,latest:row.created_at,previous:null};item.versions++;if(row.created_at>=item.latest){item.previous=item.latest;item.latest=row.created_at}map.set(key,item);return map},new Map()).values()].filter(row=>row.versions>1)
  const commitTrace=gitRows.map(row=>{const nearby=events.find(event=>event.kind!=='git.state'&&Math.abs(new Date(event.occurred_at)-new Date(row.occurred_at))<3600000);return{title:String(row.head_commit||'').slice(0,12)||'Unknown commit',branch:row.branch,machine:row.machine,objective:nearby?.objective_title||null,reason:nearby?.summary||'No nearby objective event',occurred_at:row.occurred_at}})
  const requirementCoverage=state.objectives.flatMap(row=>{const criteria=String(row.success_criteria||'').split(/\n|;/).map(value=>value.trim()).filter(Boolean);return(criteria.length?criteria:['No explicit success criterion']).map(criterion=>({title:criterion,objective_title:row.title,status:row.status,covered:evidence.some(item=>item.objective_id===row.id&&item.status==='available')}))})
  const assumptions=events.filter(row=>row.assertion==='agent_statement'||row.payload.assumption||row.payload.assumptions).map(row=>({title:row.payload.assumption||row.summary,objective_title:row.objective_title,status:row.payload.confirmed===true?'confirmed':row.payload.rejected===true?'rejected':'open',actor:row.actor,occurred_at:row.occurred_at}))
  const technicalDebt=events.filter(row=>row.payload.technical_debt||row.payload.debt||/technical debt|tech debt|todo|workaround/i.test(row.summary)).map(row=>({title:row.summary,detail:row.payload.technical_debt||row.payload.debt||row.payload.detail||'Recorded debt',objective_title:row.objective_title,due:row.payload.due||null,status:row.payload.status||'open'}))
  const securityEvidence=evidence.filter(row=>/security|audit|secret|vulnerab|sast|dependency/i.test(`${row.type} ${row.origin} ${row.label}`)).map(row=>({title:row.label,status:row.status,hash:Boolean(row.sha256),objective_title:row.objective_title,created_at:row.created_at}))
  const performanceBaselines=events.filter(row=>['duration_ms','memory_bytes','bundle_bytes','fps','latency_ms'].some(key=>row.payload[key]!==undefined)).map(row=>({title:row.summary,metrics:Object.fromEntries(['duration_ms','memory_bytes','bundle_bytes','fps','latency_ms'].filter(key=>row.payload[key]!==undefined).map(key=>[key,row.payload[key]])),occurred_at:row.occurred_at,objective_title:row.objective_title}))
  const environmentMatrix=[...events.filter(row=>row.kind==='git.state'||row.payload.os||row.payload.runtime).reduce((map,row)=>{const key=row.payload.machine||row.machine_id||'unknown',current=map.get(key)||{title:key,machine:key,os:null,runtime:null,branch:null,commit:null,observed_at:null};current.os=row.payload.os||current.os;current.runtime=row.payload.runtime||current.runtime;current.branch=row.payload.branch||current.branch;current.commit=row.payload.head_commit||current.commit;current.observed_at=row.occurred_at;map.set(key,current);return map},new Map()).values()]
  const ownershipMap=state.objectives.map(row=>{const scoped=events.filter(event=>event.objective_id===row.id),actors=[...new Set(scoped.map(event=>event.actor).filter(Boolean))];return{uid:row.uid,title:row.title,owners:actors.slice(0,5),unowned:actors.length===0}})
  const reviewCoverage=state.objectives.map(row=>{const producers=[...new Set(events.filter(event=>event.objective_id===row.id&&!['verdict.recorded','human_judgment.requested'].includes(event.kind)).map(event=>event.actor))],reviewers=[...new Set(verdicts.filter(item=>item.objective_id===row.id).map(item=>item.actor))],independent=reviewers.some(reviewer=>!producers.includes(reviewer));return{uid:row.uid,title:row.title,producers,reviewers,reviewed:reviewers.length>0,independent}})
  const verificationPolicy=reviewCoverage.map(row=>({title:row.title,required:state.objectives.find(item=>item.uid===row.uid)?.priority<=25?'human_or_independent_agent':'independent_agent_for_proven',satisfied:row.independent||state.objectives.find(item=>item.uid===row.uid)?.status!=='proven',reviewers:row.reviewers}))
  const knowledgeGaps=state.objectives.filter(row=>!row.intent||!row.success_criteria||!events.some(event=>event.objective_id===row.id)||!evidence.some(item=>item.objective_id===row.id)).map(row=>({uid:row.uid,title:row.title,missing:[!row.intent&&'intent',!row.success_criteria&&'success criteria',!events.some(event=>event.objective_id===row.id)&&'history',!evidence.some(item=>item.objective_id===row.id)&&'evidence'].filter(Boolean)}))
  const releaseNarrative=events.slice(0,30).filter(row=>['objective.updated','evidence.recorded','decision.recorded','verdict.recorded','cleanup.observed','cleanup.recorded'].includes(row.kind)).map(row=>({title:row.summary,kind:row.kind,objective_title:row.objective_title,occurred_at:row.occurred_at}))
  const incidentTimeline=state.blockers.map(blocker=>{const objective=state.objectives.find(row=>row.id===blocker.objective_id),history=events.filter(row=>row.objective_id===blocker.objective_id&&(['blocker.opened','blocker.resolved','verdict.recorded'].includes(row.kind)||row.kind==='work.finished'&&row.payload.outcome==='failed'));return{title:blocker.title,objective_title:objective?.title,events:history.length,latest:history[0]?.occurred_at||blocker.created_at,status:blocker.status}})
  const inferredTemplate={title:/unity|game|nationfall|blockrise|atlas/i.test(`${project.name} ${project.description||''}`)?'Game / Unity evidence contract':/laravel|vue|api|saas/i.test(`${project.name} ${project.description||''}`)?'Web / SaaS evidence contract':'General software evidence contract',required:['success criteria','automated test evidence','Git state','independent verdict','cleanup record'],coverage:releaseChecks.filter(row=>row.pass).length}
  const normalized=value=>String(value||'').toLowerCase().replace(/\b\d+\b/g,'#').replace(/[^a-z# ]+/g,' ').replace(/\s+/g,' ').trim()
  const otherProjectPatterns=db.prepare("SELECT p.slug,p.name,e.summary,e.kind FROM events e JOIN projects p ON p.id=e.project_id WHERE p.id!=? ORDER BY e.id DESC LIMIT 1000").all(project.id),localPatterns=new Set(events.map(row=>normalized(row.summary)).filter(value=>value.length>12)),portfolioReuse=[...otherProjectPatterns.reduce((map,row)=>{const key=normalized(row.summary);if(!localPatterns.has(key))return map;const item=map.get(key)||{title:row.summary,projects:new Set(),kind:row.kind};item.projects.add(row.name);map.set(key,item);return map},new Map()).values()].map(row=>({...row,projects:[...row.projects]}))
  const feasibleObjectives=activeObjectives.filter(row=>row.feasible).sort((a,b)=>a.priority-b.priority)
  const next=decisionQueue[0]?{kind:'decision',title:decisionQueue[0].title,reason:'Human judgment blocks further confidence',target:{view:'chapters',objective_uid:decisionQueue[0].objective_uid}}:state.blockers[0]?{kind:'blocker',title:state.blockers[0].title,reason:'Resolve the oldest active blocker',target:{view:'evidence',objective_uid:state.objectives.find(row=>row.id===state.blockers[0].objective_id)?.uid||null}}:coordination.active.find(row=>row.stale||row.overlaps.length)?{kind:'coordination',title:'Refresh Git context before continuing',reason:'An active pass is stale or overlaps another pass',target:{view:'overview'}}:feasibleObjectives[0]?{kind:'objective',title:feasibleObjectives[0].title,reason:'Highest-priority feasible objective; all recorded prerequisites are proven',target:{view:'chapters',objective_uid:feasibleObjectives[0].uid}}:activeObjectives[0]?{kind:'dependency',title:'Complete an objective prerequisite',reason:`${activeObjectives.length} unfinished objectives are currently blocked by status or dependencies`,target:{view:'diagram'}}:{kind:'review',title:'Review release readiness',reason:'No unfinished objective currently requires work',target:{view:'ai'}}
  const handoff={project:project.name,generated_at:nowStamp(),git:latestGit,active_passes:coordination.active.map(row=>({session_id:row.session_id,machine:row.machine,branch:row.branch,paths:row.paths,status:row.status,overlaps:row.overlaps})),next,blockers:state.blockers.map(row=>row.title),pending_decisions:decisionQueue.map(row=>row.title),latest:events.slice(0,8).map(compact)}
  const features=[
    feature('work_inbox','AI work inbox',activeObjectives.length?'attention':'ready',`${activeObjectives.length} unfinished objectives · ${coordination.active.length} active passes`,activeObjectives.slice(0,8).map(row=>({title:row.title,status:row.status,priority:row.priority,uid:row.uid})),activeObjectives.length),
    feature('handoff','Conversation handoff','ready','Portable context for Codex or Claude',[next,...handoff.latest.slice(0,4)],handoff.latest.length),
    feature('git_guard','Git freshness guard',!latestGit?'warning':latestGit.dirty||coordination.counts.stale||coordination.counts.conflicts?'attention':'ready',!latestGit?'No Git state reported':`${latestGit.branch} · ${String(latestGit.head_commit||'').slice(0,10)} · ${latestGit.dirty?'dirty':'clean'}`,coordination.active,coordination.counts.stale+coordination.counts.conflicts),
    feature('evidence_quality','Evidence quality',evidenceDebt.length?'attention':'ready',`${evidence.length-evidenceDebt.length}/${evidence.length} available and hashed`,evidenceDebt.map(row=>({title:row.label,status:row.status,hash:Boolean(row.sha256),objective_title:row.objective_title})),evidence.length?Math.round((evidence.length-evidenceDebt.length)/evidence.length*100):0),
    feature('failure_intelligence','Failure intelligence',groupedFailures.length?'warning':'ready',`${failures.length} failed or inconclusive attempts grouped into ${groupedFailures.length} patterns`,groupedFailures,failures.length),
    feature('ai_budget','AI budget','ready',`${costs.length} reported usage records`,agentRows,Number(costs.filter(row=>row.known).reduce((sum,row)=>sum+(row.amount||0),0).toFixed(4))),
    feature('decision_queue','Decision queue',decisionQueue.length?'attention':'ready',decisionQueue.length?'Human judgment is required only where explicitly requested':'No human judgment requested',decisionQueue,decisionQueue.length),
    feature('project_pulse','Project pulse',confidence.label==='low'?'attention':confidence.label==='medium'?'warning':'ready',`${state.objectives.filter(row=>row.status==='proven').length}/${state.objectives.length} proven · confidence ${confidence.score}`,events.slice(0,12).map(compact),confidence.score),
    feature('context_drift','Context drift alerts',contradictions.length||coordination.counts.stale?'attention':'ready',`${contradictions.length} state contradictions · ${coordination.counts.stale} stale passes`,contradictions,contradictions.length+coordination.counts.stale),
    feature('agent_sdk','Agent-ready SDK','ready','Passive CLI accepts declared observations and evidence',[{command:'orchestrator status'},{command:'orchestrator record observation.json'},{command:'orchestrator evidence add <file>'},{command:'orchestrator enable | disable'}],4),
    feature('session_replay','Session replay',events.length?'ready':'empty',`${events.length} immutable events can be replayed chronologically`,events.slice(0,12).map(compact),events.length),
    feature('done_contracts','Definition-of-done contracts',doneContracts.some(row=>row.status==='proven'&&!row.ready)?'warning':'ready',`${doneContracts.filter(row=>row.ready).length}/${doneContracts.length} objectives have criteria, proof and passing verdict`,doneContracts,doneContracts.filter(row=>row.ready).length),
    feature('proof_expiry','Proof expiry',expired.length?'warning':'ready',`${expired.length} proofs predate later objective activity`,expired.map(row=>({title:row.label,objective_title:row.objective_title,created_at:row.created_at})),expired.length),
    feature('impact_map','Impact map',evidence.length?'ready':'empty','Objectives linked to evidence, decisions and recent events',state.objectives.map(row=>({uid:row.uid,title:row.title,evidence:evidence.filter(item=>item.objective_id===row.id).length,decisions:decisions.filter(item=>item.objective_id===row.id).length,events:row.event_count})),state.objectives.length),
    feature('branch_comparison','Branch comparison',branches.length>1?'warning':'ready',`${branches.length} reported branches across machines`,branches,branches.length),
    feature('prompt_registry','Prompt registry',prompts.length?'ready':'empty',`${prompts.length} versioned or declared prompts`,prompts,prompts.length),
    feature('model_scorecard','Model performance scorecard',agentRows.length?'ready':'empty','Reported cost, tokens, successful verdicts and failures by agent',agentRows,agentRows.length),
    feature('risk_register','Risk register',risks.length?'attention':'ready',`${risks.length} derived risks from blockers, evidence and coordination`,risks,risks.length),
    feature('release_readiness','Release readiness',releaseChecks.every(row=>row.pass)?'ready':'attention',`${releaseChecks.filter(row=>row.pass).length}/${releaseChecks.length} passive release checks pass`,releaseChecks,releaseChecks.filter(row=>row.pass).length),
    feature('memory_hygiene','Memory hygiene',duplicates.length||contradictions.length?'warning':'ready',`${duplicates.length} repeated summaries · ${contradictions.length} contradictions`,[...duplicates,...contradictions],duplicates.length+contradictions.length),
    feature('next_work','What should I work on next?','ready',next.reason,[next],1),
    feature('architecture_decisions','Architecture decision records',architectureDecisions.length?'ready':'empty',`${architectureDecisions.length} versioned technical or product decisions`,architectureDecisions,architectureDecisions.length),
    feature('dependency_radar','Dependency radar',dependencySignals.length?'warning':'empty',`${dependencySignals.length} dependency observations`,dependencySignals,dependencySignals.length),
    feature('test_coverage_map','Test coverage map',testCoverage.some(row=>!row.covered)?'warning':'ready',`${testCoverage.filter(row=>row.covered).length}/${testCoverage.length} objectives linked to test evidence`,testCoverage,testCoverage.filter(row=>row.covered).length),
    feature('regression_watchlist','Regression watchlist',regressionWatch.length?'attention':'ready',`${regressionWatch.length} reopened or previously failed objectives`,regressionWatch,regressionWatch.length),
    feature('evidence_diff','Evidence diff viewer',evidenceDiffs.length?'ready':'empty',`${evidenceDiffs.length} comparable evidence series`,evidenceDiffs,evidenceDiffs.length),
    feature('commit_traceability','Commit-to-objective traceability',commitTrace.some(row=>!row.objective)?'warning':'ready',`${commitTrace.filter(row=>row.objective).length}/${commitTrace.length} Git observations linked to nearby objectives`,commitTrace,commitTrace.length),
    feature('requirement_coverage','Requirement coverage',requirementCoverage.some(row=>!row.covered)?'warning':'ready',`${requirementCoverage.filter(row=>row.covered).length}/${requirementCoverage.length} criteria have evidence`,requirementCoverage,requirementCoverage.filter(row=>row.covered).length),
    feature('assumption_register','Assumption register',assumptions.some(row=>row.status==='open')?'warning':'ready',`${assumptions.filter(row=>row.status==='open').length} open agent assumptions`,assumptions,assumptions.length),
    feature('technical_debt','Technical-debt ledger',technicalDebt.length?'warning':'ready',`${technicalDebt.length} explicitly recorded debt items`,technicalDebt,technicalDebt.length),
    feature('security_center','Security evidence center',securityEvidence.length?'ready':'empty',`${securityEvidence.length} security-related evidence records`,securityEvidence,securityEvidence.length),
    feature('performance_baseline','Performance baseline',performanceBaselines.length?'ready':'empty',`${performanceBaselines.length} measured performance records`,performanceBaselines,performanceBaselines.length),
    feature('environment_matrix','Environment matrix',environmentMatrix.length?'ready':'empty',`${environmentMatrix.length} observed machine environments`,environmentMatrix,environmentMatrix.length),
    feature('ownership_map','Ownership map',ownershipMap.some(row=>row.unowned)?'warning':'ready',`${ownershipMap.filter(row=>!row.unowned).length}/${ownershipMap.length} objectives have recorded contributors`,ownershipMap,ownershipMap.filter(row=>!row.unowned).length),
    feature('review_coverage','Review coverage',reviewCoverage.some(row=>row.reviewed&&!row.independent)?'warning':'ready',`${reviewCoverage.filter(row=>row.independent).length}/${reviewCoverage.length} objectives independently reviewed`,reviewCoverage,reviewCoverage.filter(row=>row.independent).length),
    feature('verification_policy','Independent-verification policy',verificationPolicy.some(row=>!row.satisfied)?'attention':'ready',`${verificationPolicy.filter(row=>row.satisfied).length}/${verificationPolicy.length} objective policies satisfied`,verificationPolicy,verificationPolicy.filter(row=>row.satisfied).length),
    feature('knowledge_gaps','Knowledge gaps',knowledgeGaps.length?'warning':'ready',`${knowledgeGaps.length} objectives miss intent, criteria, history or evidence`,knowledgeGaps,knowledgeGaps.length),
    feature('release_narrative','Release narrative',releaseNarrative.length?'ready':'empty',`${releaseNarrative.length} evidence-backed release changes`,releaseNarrative,releaseNarrative.length),
    feature('incident_timeline','Incident timeline',incidentTimeline.length?'attention':'ready',`${incidentTimeline.length} active incident timelines`,incidentTimeline,incidentTimeline.length),
    feature('project_template','Project template','ready',inferredTemplate.title,[inferredTemplate],inferredTemplate.coverage),
    feature('portfolio_intelligence','Portfolio intelligence',portfolioReuse.length?'ready':'empty',`${portfolioReuse.length} recurring patterns shared with other projects`,portfolioReuse,portfolioReuse.length)
  ]
  return{format:'orchestrator-ai-workspace',version:1,generated_at:nowStamp(),project:{uid:project.uid,slug:project.slug,name:project.name,status:project.status},summary:{features:features.length,ready:features.filter(row=>row.status==='ready').length,attention:features.filter(row=>row.status==='attention').length,warnings:features.filter(row=>row.status==='warning').length,confidence:confidence.score},next,handoff,features}
}

export function handoffMarkdown(workspace){
  const h=workspace.handoff,lines=[`# ${h.project} — AI handoff`,'',`Generated: ${h.generated_at}`,'',`## Next recommended work`,'',`**${h.next.title}** — ${h.next.reason}`,'',`## Git state`,'',h.git?`- ${h.git.branch} · ${h.git.head_commit} · ${h.git.dirty?'dirty':'clean'}`:'- No Git state reported','','## Active passes','']
  for(const row of h.active_passes)lines.push(`- ${row.session_id} · ${row.machine} · ${row.branch} · ${row.status} · ${row.paths.join(', ')}`)
  if(!h.active_passes.length)lines.push('- None')
  lines.push('','## Blockers','',...(h.blockers.length?h.blockers.map(value=>`- ${value}`):['- None']),'','## Pending decisions','',...(h.pending_decisions.length?h.pending_decisions.map(value=>`- ${value}`):['- None']),'','## Latest memory','',...h.latest.map(row=>`- ${row.occurred_at} · ${row.kind} · ${row.summary}`),'','Orchestrator is observation-only. Verify Git state before editing; do not infer execution authority from this handoff.','')
  return lines.join('\n')
}
