import { createHash } from 'node:crypto'
import { base, json, nowStamp, uid } from './db/index.js'

const domains={hair:/\b(hair|cheveux|coiffure|barbe|fur|pelage)\b/i,visual:/\b(design|visual|visuel|graphique|mesh|texture|shader|animation|silhouette|lisibilit|readability)\b/i,ui:/\b(ui|ux|interface|modal|layout|responsive|accessibilit|contrast|couleur|color)\b/i,performance:/\b(performance|fps|latency|latence|memory|memoire|cpu|gpu|bundle|slow|lent|regression)\b/i,testing:/\b(test|playmode|editmode|playwright|coverage|validation|verdict|proof|preuve)\b/i,data:/\b(data|database|sql|migration|cache|state|etat|save|load|persistence)\b/i,api:/\b(api|http|endpoint|auth|token|cors|request|response)\b/i,git:/\b(git|branch|commit|merge|push|dirty|stale)\b/i,build:/\b(build|compile|import|dependency|package|deployment|deploy)\b/i,game:/\b(game|unity|scene|prefab|gameplay|hud|camera|player)\b/i}
const failureKinds=new Set(['blocker.opened']),successKinds=new Set(['blocker.resolved'])
const clean=value=>String(value||'').replace(/\s+/g,' ').trim()
const tagsFor=value=>Object.entries(domains).filter(([,pattern])=>pattern.test(value)).map(([tag])=>tag)
const issueKey=value=>clean(value).toLowerCase().replace(/`[^`]+`/g,' ').replace(/\b[a-z]{1,5}[-_]?\d+[a-z0-9_-]*\b/g,' ').replace(/\b[0-9a-f]{7,}\b/g,' ').replace(/[^a-zà-ÿ]+/gi,' ').split(/\s+/).filter(word=>word.length>3&&!['avec','dans','pour','from','that','this','with','have','mais','plus','sans','been','were','when','then','after','avant','apres','comme','status','verdict','evidence','preuve','error','erreur','failure','failed','defect','defaut','regression','crash','broken'].includes(word)).slice(0,14).sort().join(':')
const failure=row=>failureKinds.has(row.kind)||row.kind==='verdict.recorded'&&['fail','inconclusive'].includes(row.payload.verdict)||row.kind==='work.finished'&&row.payload.outcome==='failed'||!(/\b(pass|passed|accept|accepted|proven|complete|completed|resolved|corrige|fixed)\b/i.test(row.summary))&&/\b(fail|failed|failure|error|erreur|bug|regression|defect|defaut|crash|broken)\b/i.test(row.summary)
const success=row=>successKinds.has(row.kind)||row.kind==='verdict.recorded'&&row.payload.verdict==='pass'||row.kind==='work.finished'&&row.payload.outcome==='completed'||row.kind==='objective.updated'&&row.payload.status==='proven'
const resolution=row=>clean(row.payload.rationale||row.payload.solution||row.payload.detail||row.payload.summary||row.summary)
const credibleResolution=value=>{const opening=clean(value).slice(0,140);return/\b(pass|passed|resolved|fixed|corrected|verified|complete|completed|accepted|source_go|closed|succeed|validate|validated|valide|corrige|resolu|exit 0|zero errors)\b/i.test(opening)&&!/^.{0,80}\b(fail|failed|reject|blocked|no-go)\b/i.test(opening)}
const fingerprint=value=>createHash('sha256').update(value).digest('hex')

export function refreshKnowledgeBase(){
  const db=base(),rows=db.prepare(`SELECT e.uid,e.project_id,e.objective_id,e.kind,e.summary,e.payload,e.occurred_at,p.slug,p.name,p.project_type FROM events e JOIN projects p ON p.id=e.project_id WHERE p.status!='archived' ORDER BY e.project_id,e.objective_id,e.occurred_at,e.id`).all().map(row=>({...row,payload:json.read(row.payload,{})})),evidence=db.prepare("SELECT project_id,objective_id,count(*) n FROM evidence_manifests WHERE status='available' AND sha256 IS NOT NULL GROUP BY project_id,objective_id").all(),proofs=new Map(evidence.map(row=>[`${row.project_id}:${row.objective_id}`,row.n])),groups=new Map(),timelines=[...rows.reduce((map,row)=>{const key=`${row.project_id}:${row.objective_id||'project'}`,timeline=map.get(key)||[];timeline.push(row);map.set(key,timeline);return map},new Map()).values()]
  for(const timeline of timelines)for(let index=0;index<timeline.length;index++){
    const failed=timeline[index]
    if(!failure(failed))continue
    const problem=clean(failed.summary),issue=issueKey(problem),problemWords=new Set(issue.split(':').filter(Boolean));if(problemWords.size<2)continue
    const candidates=timeline.slice(index+1,index+151).filter(row=>success(row)).map(row=>{const solution=resolution(row),solutionWords=new Set(issueKey(`${row.summary} ${solution}`).split(':').filter(Boolean)),overlap=[...problemWords].filter(word=>solutionWords.has(word)).length,sameBlocker=failed.payload.blocker_uid&&failed.payload.blocker_uid===row.payload.blocker_uid;return{row,solution,score:overlap+(sameBlocker?3:0)}}).filter(item=>item.solution.length>=12&&item.score>1&&credibleResolution(item.solution)).sort((a,b)=>b.score-a.score||a.row.occurred_at.localeCompare(b.row.occurred_at))
    const solved=candidates[0]?.row,solution=candidates[0]?.solution;if(!solved)continue
    const combined=`${problem} ${JSON.stringify(failed.payload)}`,tags=[...new Set([failed.project_type,...tagsFor(combined)])],key=`${tags.filter(tag=>tag!==failed.project_type).slice(0,2).sort().join(':')||failed.project_type}:${issue}`,item=groups.get(key)||{key,tags:new Set(),projects:new Set(),sources:new Set(),proofKeys:new Set(),failures:[],solutions:[],first:failed.occurred_at,last:solved.occurred_at,verified:0}
    tags.forEach(tag=>item.tags.add(tag));item.projects.add(failed.slug);item.sources.add(failed.uid);item.sources.add(solved.uid);item.failures.push(problem);item.solutions.push(solution);const proofKey=`${failed.project_id}:${failed.objective_id}`;if(!item.proofKeys.has(proofKey)){item.proofKeys.add(proofKey);item.verified+=Math.min(5,proofs.get(proofKey)||0)}item.first=item.first<failed.occurred_at?item.first:failed.occurred_at;item.last=item.last>solved.occurred_at?item.last:solved.occurred_at;groups.set(key,item)
  }
  const detected=[]
  for(const item of groups.values()){
    const projects=[...item.projects],occurrences=item.failures.length;if(occurrences<2&&projects.length<2&&item.verified<2)continue
    const confidence=Math.min(95,45+Math.min(20,occurrences*8)+Math.min(15,projects.length*7)+Math.min(15,item.verified*3)),status=occurrences>=2||projects.length>=2?'active':'candidate',problem=item.failures.at(-1),recommendation=item.solutions.at(-1),title=`${[...item.tags].filter(tag=>!['software','web','api','mobile','ai','infrastructure','documentation','other'].includes(tag)).slice(0,2).join(' + ')||'Delivery'} lesson: ${problem.slice(0,90)}`,hash=fingerprint(`${item.key}:${problem.toLowerCase().replace(/\d+/g,'#').slice(0,180)}`),existing=db.prepare('SELECT * FROM knowledge_rules WHERE fingerprint=?').get(hash),ruleUid=existing?.uid||uid(),manual=existing?.source_events?.includes('"manual"'),finalStatus=existing?.status==='dismissed'?'dismissed':manual?'active':status
    db.prepare(`INSERT INTO knowledge_rules(uid,fingerprint,title,problem,recommendation,avoid_text,tags,project_slugs,source_events,confidence,occurrences,status,first_seen_at,last_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET title=excluded.title,problem=excluded.problem,recommendation=excluded.recommendation,avoid_text=excluded.avoid_text,tags=excluded.tags,project_slugs=excluded.project_slugs,source_events=CASE WHEN knowledge_rules.source_events LIKE '%"manual"%' THEN knowledge_rules.source_events ELSE excluded.source_events END,confidence=excluded.confidence,occurrences=excluded.occurrences,status=CASE WHEN knowledge_rules.status='dismissed' THEN 'dismissed' WHEN knowledge_rules.source_events LIKE '%"manual"%' THEN 'active' ELSE excluded.status END,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at`).run(ruleUid,hash,title,problem,recommendation,problem,json.write([...item.tags]),json.write(projects),json.write([...item.sources]),confidence,occurrences,finalStatus,item.first,item.last,nowStamp())
    detected.push(ruleUid)
  }
  if(detected.length){const placeholders=detected.map(()=>'?').join(',');db.prepare(`DELETE FROM knowledge_rules WHERE source_events!='[]' AND source_events NOT LIKE '%"manual"%' AND uid NOT IN (${placeholders})`).run(...detected)}else db.prepare("DELETE FROM knowledge_rules WHERE source_events!='[]' AND source_events NOT LIKE '%\"manual\"%'").run()
  return knowledgeBase({refresh:false,detected:detected.length})
}

export function knowledgeBase({refresh=true,detected=null}={}){if(refresh)return refreshKnowledgeBase();const rows=base().prepare("SELECT * FROM knowledge_rules ORDER BY status='active' DESC,confidence DESC,last_seen_at DESC").all().map(row=>({...row,tags:json.read(row.tags,[]),project_slugs:json.read(row.project_slugs,[]),source_events:json.read(row.source_events,[])}));return{format:'orchestrator-knowledge-base',version:1,generated_at:nowStamp(),summary:{rules:rows.length,active:rows.filter(row=>row.status==='active').length,candidates:rows.filter(row=>row.status==='candidate').length,projects:new Set(rows.flatMap(row=>row.project_slugs)).size,detected},rules:rows,execution:false}}

export function applicableKnowledge(projectValue,{refresh=true}={}){const db=base(),project=typeof projectValue==='object'?projectValue:db.prepare('SELECT * FROM projects WHERE slug=? OR uid=?').get(projectValue,projectValue);if(!project)return[];const objectiveText=db.prepare("SELECT group_concat(title||' '||coalesce(intent,'')||' '||coalesce(success_criteria,''),' ') text FROM objectives WHERE project_id=?").get(project.id)?.text||'',haystack=`${project.name} ${project.description||''} ${objectiveText}`,signals=new Set(tagsFor(haystack)),rules=knowledgeBase({refresh}).rules.filter(row=>row.status==='active').map(row=>{const matched=row.tags.filter(tag=>tag!==project.project_type&&signals.has(tag)),sameType=row.tags.includes(project.project_type),direct=row.project_slugs.includes(project.slug);return{...row,relevance:Math.min(100,(sameType?10:0)+(direct?5:0)+matched.length*30+row.confidence*.25),matched_tags:matched,source_project:direct}}).filter(row=>row.relevance>=40).sort((a,b)=>b.relevance-a.relevance);return rules.slice(0,30)}

export function updateKnowledgeRule(ruleUid,input){const status=['candidate','active','dismissed'].includes(input.status)?input.status:null,recommendation=clean(input.recommendation),avoid=clean(input.avoid_text),row=base().prepare('SELECT * FROM knowledge_rules WHERE uid=?').get(ruleUid);if(!row)throw Object.assign(new Error('Unknown knowledge rule.'),{status:404});const sources=json.read(row.source_events,[]),marked=status==='active'?[...new Set([...sources,'manual'])]:sources.filter(value=>value!=='manual');base().prepare('UPDATE knowledge_rules SET status=?,recommendation=?,avoid_text=?,source_events=?,updated_at=? WHERE uid=?').run(status||row.status,recommendation||row.recommendation,avoid||row.avoid_text,json.write(marked),nowStamp(),ruleUid);return knowledgeBase({refresh:false}).rules.find(item=>item.uid===ruleUid)}

export function createKnowledgeRule(projectValue,input={}){const db=base(),project=typeof projectValue==='object'?projectValue:db.prepare('SELECT * FROM projects WHERE slug=? OR uid=?').get(projectValue,projectValue);if(!project)throw Object.assign(new Error('Unknown project.'),{status:404});const title=clean(input.title),recommendation=clean(input.recommendation),problem=clean(input.problem)||`Contexte de ${title}`,avoid=clean(input.avoid_text)||'Ne pas perdre ce contexte lors des prochaines passes.';if(!title||!recommendation)throw Object.assign(new Error('A title and recommendation are required.'),{status:400});const stamp=nowStamp(),hash=fingerprint(`manual:${project.slug}:${title.toLowerCase()}`),existing=db.prepare('SELECT uid FROM knowledge_rules WHERE fingerprint=?').get(hash),ruleUid=existing?.uid||uid(),tags=[...new Set([project.project_type,...tagsFor(`${title} ${problem} ${recommendation}`)])],sources=[...new Set([...(Array.isArray(input.source_events)?input.source_events:[]).map(String),'manual'])];db.prepare(`INSERT INTO knowledge_rules(uid,fingerprint,title,problem,recommendation,avoid_text,tags,project_slugs,source_events,confidence,occurrences,status,first_seen_at,last_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,100,1,'active',?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET problem=excluded.problem,recommendation=excluded.recommendation,avoid_text=excluded.avoid_text,tags=excluded.tags,project_slugs=excluded.project_slugs,source_events=excluded.source_events,confidence=100,status='active',last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at`).run(ruleUid,hash,title,problem,recommendation,avoid,json.write(tags),json.write([project.slug]),json.write(sources),stamp,stamp,stamp);return knowledgeBase({refresh:false}).rules.find(item=>item.uid===ruleUid)}
