import { closeSync, existsSync, openSync, readFileSync, readSync, readdirSync, statSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { homedir } from 'node:os'
import { basename, join, relative, resolve } from 'node:path'
import { base } from './db/index.js'

function files(root){try{return readdirSync(root,{recursive:true,withFileTypes:true}).filter(entry=>entry.isFile()&&entry.name.endsWith('.jsonl')).map(entry=>join(entry.parentPath||entry.path,entry.name))}catch{return[]}}
function head(file){const descriptor=openSync(file,'r'),buffer=Buffer.allocUnsafe(65536);try{return buffer.subarray(0,readSync(descriptor,buffer,0,buffer.length,0)).toString('utf8')}finally{closeSync(descriptor)}}
export function scanLocalMemories(){const roots=[['codex',join(homedir(),'.codex','sessions')],['codex',join(homedir(),'.codex','archived_sessions')],['claude',join(homedir(),'.claude','projects')]],projects=new Map(),inventories=[],manifests=[];for(const[source,root]of roots){const entries=files(root);let parsed=0,partial=0;for(const file of entries){let text='';try{text=head(file)}catch(error){manifests.push({source,adapter_version:1,path:file,status:'error',sha256:null,records_found:0,parse_errors:1,detail:error.message});partial++;continue}const lines=text.split('\n').filter(Boolean),valid=lines.reduce((count,line)=>{try{JSON.parse(line);return count+1}catch{return count}},0),errors=lines.length-valid,cwd=text.match(/"cwd"\s*:\s*"([^"]+)"/)?.[1]?.replace(/\\\//g,'/'),status=cwd?(errors?'partial':'parsed'):'unsupported';manifests.push({source,adapter_version:1,path:file,status,sha256:createHash('sha256').update(text).digest('hex'),records_found:valid,parse_errors:errors,detail:cwd?null:'No working directory found in sampled records'});if(status==='parsed')parsed++;else partial++;if(!cwd||cwd==='/'||cwd.includes('/.codex')||cwd.includes('/.claude'))continue;const name=basename(cwd),key=cwd.toLowerCase(),modified=statSync(file).mtime.toISOString(),row=projects.get(key)||{name,path:cwd,sources:new Set(),sessions:0,last_activity:modified};row.sources.add(source);row.sessions++;if(modified>row.last_activity)row.last_activity=modified;projects.set(key,row)}inventories.push({source,root,files:entries.length,parsed,partial,adapter_version:1})}return{format:'orchestrator-local-memory-scan',version:1,scanned_at:new Date().toISOString(),inventories,manifests,projects:[...projects.values()].map(row=>({...row,sources:[...row.sources]})).sort((a,b)=>b.last_activity.localeCompare(a.last_activity))}}

const recoveryExtensions=/\.(?:png|jpe?g|webp|gif|pdf|md|json|txt|log|csv|xml|html?)$/i
const recoverySignal=/(?:proof|evidence|capture|screenshot|report|result|test|review|artifact|output|trace|baseline|verdict|validation|metrics|benchmark|playwright)/i
function strings(value,out=[]){if(typeof value==='string')out.push(value);else if(Array.isArray(value))for(const item of value)strings(item,out);else if(value&&typeof value==='object')for(const item of Object.values(value))strings(item,out);return out}
function pathsFrom(value){const found=[];for(const text of strings(value)){const normalized=text.replaceAll('\\/','/');for(const match of normalized.matchAll(/(?:^|[\s"'`(])((?:\/Applications|\/Users|\/private\/(?:tmp|var)|\/tmp|\/var)\/[^\s"'`<>|),;]+\.[A-Za-z0-9]{1,8})(?=$|[\s"'`),;:<>])/g)){const path=match[1].replace(/[.,:;]+$/,'');if(recoveryExtensions.test(path)&&(recoverySignal.test(path)||/\.(?:png|jpe?g|webp|gif|pdf)$/i.test(path)))found.push(path)}}return found}
const projectRoot=project=>String(project.description||'').match(/Repository:\s*(.+)/i)?.[1]?.trim()||null
function belongsToProject(path,root){const relation=relative(resolve(root),resolve(path));return relation===''||(!relation.startsWith('..')&&!relation.startsWith('/'))}
function messageText(record){const content=record?.message?.content;if(typeof content==='string')return content;if(!Array.isArray(content))return'';return content.filter(item=>item?.type==='text'&&typeof item.text==='string').map(item=>item.text).join(' ')}
const conversationContent=value=>{if(typeof value==='string')return value;if(!Array.isArray(value))return'';return value.filter(item=>item&&['text','input_text','output_text'].includes(item.type)&&typeof item.text==='string').map(item=>item.text).join('\n')}
export function localConversationSession(source){
  const path=String(source?.source_file||''),provider=String(source?.provider||source?.source||'unknown');if(!path.endsWith('.jsonl')||!existsSync(path))throw Object.assign(new Error('Conversation history is not available on this machine.'),{status:404})
  const stat=statSync(path);if(!stat.isFile()||stat.size>50*1024*1024)throw Object.assign(new Error('Conversation history is too large to open safely.'),{status:413})
  const messages=[],records=readFileSync(path,'utf8').split('\n');let sessionId=null,title=null
  for(let index=0;index<records.length;index++){let record;try{record=JSON.parse(records[index])}catch{continue}sessionId||=record.sessionId||record.session_id||record.payload?.id||null;title||=record.aiTitle||record.payload?.title||null;let role=record.message?.role||record.payload?.role||(['user','assistant'].includes(record.type)?record.type:null),content=conversationContent(record.message?.content??record.payload?.content)
    if(!role&&record.type==='event_msg'&&['user_message','agent_message'].includes(record.payload?.type)){role=record.payload.type==='user_message'?'user':'assistant';content=String(record.payload.message||'')}
    if(!['user','assistant'].includes(role)||!content.trim())continue
    messages.push({line:index+1,role,content:content.trim(),occurred_at:record.timestamp||record.created_at||record.time||stat.mtime.toISOString(),timestamp_source:record.timestamp||record.created_at||record.time?'message':'file'})
  }
  return{provider,session_id:String(sessionId||basename(path,'.jsonl')),title:String(title||`${provider==='claude'?'Claude':'Codex'} · session historique`),source_file:path,messages,available:true}
}
export function recentLocalConversationActivity(project,{since=null,limit=50,memoryRoots=null}={}){
  const root=projectRoot(project);if(!root)return[]
  const roots=memoryRoots||[['codex',join(homedir(),'.codex','sessions')],['codex',join(homedir(),'.codex','archived_sessions')],['claude',join(homedir(),'.claude','projects')]],cutoff=since&&Date.parse(since)?Date.parse(since):Date.now()-7*86400000,rows=new Map()
  for(const[source,memoryRoot]of roots)for(const file of files(memoryRoot)){let stat;try{stat=statSync(file);if(stat.mtimeMs<cutoff||stat.size>50*1024*1024)continue}catch{continue}let records;try{records=readFileSync(file,'utf8').split('\n').map((line,index)=>{try{return{record:JSON.parse(line),index}}catch{return null}}).filter(Boolean)}catch{continue}for(let position=0;position<records.length;position++){const{record,index}=records[position];if(record.type!=='assistant')continue;const timestamp=record.timestamp||record.created_at||record.time||stat.mtime.toISOString();if(Number.isNaN(Date.parse(timestamp))||Date.parse(timestamp)<cutoff)continue;const cwd=String(record.cwd||record.payload?.cwd||'');if(!belongsToProject(cwd||'/',root))continue;const add=(role,item,itemIndex)=>{const text=messageText(item).replace(/\s+/g,' ').trim();if(text.length<20)return;const occurred=item.timestamp||item.created_at||item.time||timestamp,digest=createHash('sha256').update(`${file}:${itemIndex+1}:${role}:${text}`).digest('hex');rows.set(digest,{source,role,source_file:file,source_line:itemIndex+1,occurred_at:new Date(occurred).toISOString(),summary:text.slice(0,1000),digest})};add('assistant',record,index);for(let previous=position-1;previous>=Math.max(0,position-80);previous--){const candidate=records[previous];if(candidate.record.type!=='user')continue;const content=candidate.record?.message?.content;if(Array.isArray(content)&&content.some(item=>item?.type==='tool_result'))continue;add('user',candidate.record,candidate.index);break}}}
  return[...rows.values()].sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).slice(0,Math.max(1,limit))
}
export function recoverLocalEvidence(project,{since=null,limit=1000,memoryRoots=null}={}){
  const root=projectRoot(project);if(!root)return{project:project.slug,since,candidates:[],sessions:0,errors:['Project repository path is not recorded.']}
  const roots=memoryRoots||[['codex',join(homedir(),'.codex','sessions')],['codex',join(homedir(),'.codex','archived_sessions')],['claude',join(homedir(),'.claude','projects')]],cutoff=since&&Date.parse(since)?new Date(since).getTime():0,candidates=new Map(),errors=[],objectiveRows=base().prepare('SELECT uid,title FROM objectives WHERE project_id=?').all(project.id)
  let sessions=0
  for(const[source,memoryRoot]of roots)for(const file of files(memoryRoot)){let stat;try{stat=statSync(file);if(stat.mtimeMs<cutoff||stat.size>50*1024*1024)continue}catch{continue}let content;try{content=readFileSync(file,'utf8')}catch(error){errors.push(`${file}: ${error.message}`);continue}const fileMentionsProject=content.includes(root)||content.toLowerCase().includes(project.name.toLowerCase());if(!fileMentionsProject)continue;sessions++;const lines=content.split('\n');for(let index=0;index<lines.length;index++){let record;try{record=JSON.parse(lines[index])}catch{continue}const rawTimestamp=record.timestamp||record.created_at||record.time||stat.mtime.toISOString(),timestamp=Number.isNaN(Date.parse(rawTimestamp))?stat.mtime.toISOString():new Date(rawTimestamp).toISOString();if(Date.parse(timestamp)<cutoff)continue;const serialized=JSON.stringify(record),cwd=record.cwd||record.payload?.cwd||serialized.match(/"cwd":"([^"]+)"/)?.[1],scoped=String(cwd||'').startsWith(root)||serialized.includes(root);if(!scoped)continue;for(const path of pathsFrom(record)){if(!belongsToProject(path,root))continue;const key=path,exists=existsSync(path);let bytes=null,sha256=null;try{const info=statSync(path);if(!info.isFile())continue;bytes=info.size;sha256=createHash('sha256').update(readFileSync(path)).digest('hex')}catch{}const nearby=serialized.toLowerCase(),objective=objectiveRows.find(row=>nearby.includes(row.uid.toLowerCase())||row.title.split(/[—-]/)[0].trim().length>=2&&nearby.includes(row.title.split(/[—-]/)[0].trim().toLowerCase())),pass=serialized.match(/(?:pass|passage)[-_ #:]*(\d+)/i)?.[1]||path.match(/(?:pass|passage)[-_ ]*(\d+)/i)?.[1]||null,current=candidates.get(key);const item={path,label:basename(path),type:/\.(?:png|jpe?g|webp|gif)$/i.test(path)?'image':/\.pdf$/i.test(path)?'report':'artifact',origin:`Recovered from local ${source} conversation`,source,source_file:file,source_line:index+1,occurred_at:timestamp,objective_uid:objective?.uid||null,pass_ref:pass,status:exists?'available':'missing',retention:exists?'referenced':'missing',bytes,sha256};if(!current||item.occurred_at>current.occurred_at)candidates.set(key,item);if(candidates.size>=limit)break}if(candidates.size>=limit)break}if(candidates.size>=limit)break}
  return{format:'orchestrator-evidence-recovery',version:1,project:project.slug,repository:root,since:since||null,scanned_at:new Date().toISOString(),sessions,candidates:[...candidates.values()].sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)),errors:errors.slice(0,20)}
}
