import { createHash } from 'node:crypto'
import { closeSync, openSync, readSync, readdirSync, statSync } from 'node:fs'
import { homedir } from 'node:os'
import { basename, join } from 'node:path'
import { base, json, nowStamp, uid } from './db/index.js'

const roots=()=>[['codex',join(homedir(),'.codex','sessions')],['codex',join(homedir(),'.codex','archived_sessions')],['claude',join(homedir(),'.claude','projects')]]
const inventories=new Map()
const workspaces=new Map()
const recentFiles=(root,cutoff,max=300)=>{let cached=inventories.get(root);if(!cached||Date.now()-cached.at>60000){try{cached={at:Date.now(),rows:readdirSync(root,{recursive:true,withFileTypes:true}).filter(entry=>entry.isFile()&&entry.name.endsWith('.jsonl')).map(entry=>{const path=join(entry.parentPath||entry.path,entry.name);try{const stat=statSync(path);return{path,mtime:stat.mtimeMs,size:stat.size}}catch{return null}}).filter(Boolean).sort((a,b)=>b.mtime-a.mtime)}}catch{cached={at:Date.now(),rows:[]}}inventories.set(root,cached)}return cached.rows.filter(row=>row.mtime>=cutoff).slice(0,max)}
const tail=(path,size,max=2*1024*1024)=>{const length=Math.min(size,max),descriptor=openSync(path,'r'),buffer=Buffer.alloc(length);try{return buffer.subarray(0,readSync(descriptor,buffer,0,length,Math.max(0,size-length))).toString('utf8')}finally{closeSync(descriptor)}}
const head=(path,size,max=128*1024)=>{const length=Math.min(size,max),descriptor=openSync(path,'r'),buffer=Buffer.alloc(length);try{return buffer.subarray(0,readSync(descriptor,buffer,0,length,0)).toString('utf8')}finally{closeSync(descriptor)}}
const digest=value=>createHash('sha256').update(String(value)).digest('hex')
const projectRoot=project=>String(project.description||'').match(/Repository:\s*(.+)/i)?.[1]?.trim()||null
const contentText=value=>{if(typeof value==='string')return value;if(!Array.isArray(value))return'';return value.filter(item=>item&&['text','input_text','output_text'].includes(item.type)&&typeof item.text==='string').map(item=>item.text).join('\n')}
const normalizeCode=value=>String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'')
const workCode=value=>String(value||'').match(/\b(?:[A-Z]{1,8}[- ]?)?\d{2,4}[A-Z0-9-]*\b/)?.[0]||null
const sessionTitle=(project,cwd,output,isPilot=false)=>{if(isPilot)return`Pilote ${project.name} — actif`;const explicit=output.match(/(?:NOM EXACT|CHAPITRE)\s*:\s*([^\n]+)/i)?.[1]?.trim();if(explicit)return explicit.slice(0,180);const folder=basename(cwd||'').replace(/-20\d\d-\d\d-\d\d.*$/,'').replaceAll('-',' ').trim();return folder||`${project.name} · session IA`}
const verdict=value=>{if(/\bFAIL VISUEL\b|\bVERDICT[^:\n]{0,40}:\s*(?:FAIL|REJET)|\bBLOQU[ÉE]/i.test(value))return'fail';if(/\bVERDICT[^:\n]{0,40}:\s*(?:PASS|ACCEPT)|\bPASS TECHNIQUE\b/i.test(value))return'pass';return null}
const extractWork=value=>{const chapter=value.match(/CHAPITRE\s*:\s*([^\n]+)/i)?.[1]?.trim(),named=value.match(/NOM EXACT\s*:\s*([^\n]+)/i)?.[1]?.trim();return(chapter||named||'').replace(/\s{2,}/g,' ').slice(0,240)}
const settingsKey=project=>`reconciliation:${project.uid}`
const settings=project=>json.read(base().prepare('SELECT value FROM management_settings WHERE key=?').get(settingsKey(project))?.value,{decisions:{}})
const saveSettings=(project,value)=>base().prepare("INSERT INTO management_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(settingsKey(project),json.write(value),nowStamp())
const normalizedPath=value=>String(value||'').replace(/\/+$/,'')
const registeredRoots=()=>base().prepare("SELECT slug,name,description FROM projects WHERE status!='archived'").all().map(row=>({...row,root:normalizedPath(String(row.description||'').match(/Repository:\s*(.+)/i)?.[1]?.trim())})).filter(row=>row.root)
const belongsToProject=(project,cwd,latest)=>{const repository=normalizedPath(projectRoot(project)),location=normalizedPath(cwd),roots=registeredRoots(),inside=Boolean(repository&&(location===repository||location.startsWith(`${repository}/`))),mentioned=roots.filter(row=>latest.includes(row.root));if(inside)return true;if(mentioned.length)return mentioned.some(row=>row.root===repository)&&!mentioned.some(row=>row.root!==repository);const escaped=String(project.name||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return Boolean(escaped&&new RegExp(`(?:PROJET|PROJECT|RACINE|REPOSITORY)\\s*:?\\s*${escaped}\\b`,'i').test(latest))}
const pilotSession=(project,cwd)=>new RegExp(`(?:^|[\\/])[^\\/]*(?:pilote|pilot)[-_ ]*${String(project.slug||project.name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?:[-_ /]|$)`,'i').test(String(cwd||''))

function localSessions(project,{days=21,limit=80,memoryRoots=null}={}){
  const cutoff=Date.now()-Math.max(1,Number(days)||21)*86400000,found=[]
  for(const[provider,root]of memoryRoots||roots())for(const file of recentFiles(root,cutoff)){const path=file.path;if(file.size>50*1024*1024)continue;let raw;try{raw=tail(path,file.size)}catch{continue}
    let id=basename(path,'.jsonl').match(/([0-9a-f]{8}-[0-9a-f-]{27,})$/i)?.[1]||null,cwd='',latest='',occurredAt=new Date(file.mtime).toISOString()
    let prefix='';try{prefix=head(path,file.size)}catch{}for(const line of prefix.split('\n')){let record;try{record=JSON.parse(line)}catch{continue}if(record.type==='session_meta'){id||=record.payload?.id;cwd||=record.payload?.cwd||'';break}}
    for(const line of raw.split('\n')){let record;try{record=JSON.parse(line)}catch{continue}const payload=record.payload||{},assistant=record.type==='response_item'&&payload.type==='message'&&payload.role==='assistant'||record.type==='event_msg'&&payload.type==='agent_message';if(!assistant)continue;const text=contentText(payload.content)||String(payload.message||'');if(!text.trim())continue;latest=text.trim();occurredAt=record.timestamp||occurredAt}
    if(!latest||!belongsToProject(project,cwd,latest))continue
    const isPilot=pilotSession(project,cwd);found.push({provider,session_id:String(id||basename(path,'.jsonl')),title:sessionTitle(project,cwd,latest,isPilot),cwd,source_file:path,last_activity:new Date(occurredAt).toISOString(),work:extractWork(latest),verdict:isPilot?null:verdict(latest),role:isPilot?'pilot':'execution',excerpt:latest.replace(/\s+/g,' ').slice(0,900)})
  }
  return found.sort((a,b)=>b.last_activity.localeCompare(a.last_activity)).slice(0,Math.max(1,limit))
}

function suggestions(project,sessions){
  const db=base(),objectives=db.prepare('SELECT * FROM objectives WHERE project_id=?').all(project.id),linkedSessions=new Set(db.prepare("SELECT provider,external_id FROM external_items WHERE project_id=? AND item_type='ai_session' AND status='linked'").all(project.id).map(row=>`${row.provider}:${row.external_id}`)),rows=[]
  const add=row=>{const fingerprint=digest([project.uid,row.action,row.objective_uid||'',row.source.provider,row.source.id,row.after||row.title].join(':'));rows.push({...row,fingerprint})}
  for(const objective of objectives.filter(row=>['draft','ready','in_progress','blocked'].includes(row.status))){const event=db.prepare("SELECT uid,actor_kind,actor,summary,payload,occurred_at FROM events WHERE project_id=? AND objective_id=? AND kind='work.finished' ORDER BY occurred_at DESC,id DESC LIMIT 1").get(project.id,objective.id);if(!event)continue;const payload=json.read(event.payload,{}),result=String(payload.verdict||'').toLowerCase(),outcome=String(payload.outcome||'').toLowerCase(),after=/pass|accept|success/.test(result)?'proven':/fail|reject|block/.test(result)||/fail|reject|block/.test(outcome)?'ready':null;if(after&&after!==objective.status)add({action:'update_status',title:`Mettre à jour « ${objective.title} »`,objective_uid:objective.uid,objective_title:objective.title,before:objective.status,after,rationale:`La dernière fin de travail enregistrée indique « ${payload.verdict||payload.outcome} ». Un échec demande une reprise, mais ne bloque le plan que si un obstacle actif est enregistré.`,observed_at:event.occurred_at,source:{provider:event.actor_kind,id:event.uid,title:event.actor,kind:'event'},excerpt:event.summary})}
  const byCode=new Map();for(const session of sessions){if(linkedSessions.has(`${session.provider}:${session.session_id}`))continue;const code=workCode(session.work);if(!code)continue;const normalized=normalizeCode(code),objective=objectives.find(row=>normalizeCode(workCode(row.title))===normalized||row.title.toLowerCase().includes(session.work.toLowerCase()));if(objective&&session.verdict){if(Date.parse(session.last_activity)<=Date.parse(objective.updated_at||objective.created_at||0))continue;const after=session.verdict==='pass'?'proven':'ready';if(after!==objective.status)add({action:'update_status',title:`Mettre à jour « ${objective.title} »`,objective_uid:objective.uid,objective_title:objective.title,before:objective.status,after,rationale:`La session ${session.provider} conclut « ${session.verdict.toUpperCase()} » sur ${session.work}. Un FAIL reste exécutable pour correction ; seul un blocage actif empêche la suite.`,observed_at:session.last_activity,source:{provider:session.provider,id:session.session_id,title:session.title,kind:'session',source_file:session.source_file},excerpt:session.excerpt})}else if(!objective&&session.work){const current=byCode.get(normalized);if(!current||session.last_activity>current.observed_at)byCode.set(normalized,{action:'create_objective',title:session.work,objective_uid:null,objective_title:null,before:null,after:'ready',rationale:`Cette passe apparaît dans une session ${session.provider} liée au projet, mais n’existe pas dans le plan Orchestrator. Elle reste disponible pour reprise${session.verdict==='fail'?' après son dernier échec':''}.`,observed_at:session.last_activity,source:{provider:session.provider,id:session.session_id,title:session.title,kind:'session',source_file:session.source_file},excerpt:session.excerpt})}}
  for(const row of byCode.values())add(row)
  const unique=new Map();for(const row of rows.sort((a,b)=>b.observed_at.localeCompare(a.observed_at)))if(!unique.has(`${row.action}:${row.objective_uid||normalizeCode(workCode(row.title))}`))unique.set(`${row.action}:${row.objective_uid||normalizeCode(workCode(row.title))}`,row)
  return[...unique.values()]
}

export function reconciliationWorkspace(project,input={}){const sessions=input.sessions||localSessions(project,input),state=settings(project),all=suggestions(project,sessions).map(row=>({...row,decision:state.decisions?.[row.fingerprint]||null})),objectives=base().prepare('SELECT uid,title,status,priority FROM objectives WHERE project_id=? ORDER BY priority,id').all(project.id),pilot=sessions.find(row=>row.role==='pilot'&&row.work),code=workCode(pilot?.work),objective=code?objectives.find(row=>normalizeCode(workCode(row.title))===normalizeCode(code)):null,focus=pilot?{source:'external_pilot',provider:pilot.provider,session_id:pilot.session_id,title:pilot.title,work:pilot.work,last_activity:pilot.last_activity,objective_uid:objective?.uid||null,objective_title:objective?.title||null,objective_status:objective?.status||null,aligned:Boolean(objective&&objectives[0]?.uid===objective.uid)}:null,workspace={project:{slug:project.slug,name:project.name},generated_at:nowStamp(),sessions,focus,suggestions:all.filter(row=>!row.decision),history:all.filter(row=>row.decision),summary:{sessions:sessions.length,pilots:sessions.filter(row=>row.role==='pilot').length,pending:all.filter(row=>!row.decision).length,accepted:all.filter(row=>row.decision==='accepted').length,rejected:all.filter(row=>row.decision==='rejected').length},execution:false};workspaces.set(project.id,workspace);return workspace}

export function reviewReconciliation(project,fingerprint,input={}){const decision=input.decision;if(!['accepted','rejected'].includes(decision))throw Object.assign(new Error('Decision must be accepted or rejected.'),{status:400});const workspace=workspaces.get(project.id)||reconciliationWorkspace(project,{days:30,limit:120}),proposal=[...workspace.suggestions,...workspace.history].find(row=>row.fingerprint===fingerprint);if(!proposal)throw Object.assign(new Error('Unknown or expired reconciliation proposal.'),{status:404});const db=base(),state=settings(project),stamp=nowStamp();if(decision==='accepted')db.transaction(()=>{let objective;if(proposal.action==='update_status'){objective=db.prepare('SELECT * FROM objectives WHERE project_id=? AND uid=?').get(project.id,proposal.objective_uid);if(!objective)throw new Error('The target objective no longer exists.');db.prepare('UPDATE objectives SET status=?,updated_at=? WHERE id=?').run(proposal.after,stamp,objective.id)}else{const priority=Number(db.prepare('SELECT max(priority) priority FROM objectives WHERE project_id=?').get(project.id)?.priority||0)+10,objectiveUid=uid();db.prepare('INSERT INTO objectives(uid,project_id,title,intent,status,priority,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(objectiveUid,project.id,proposal.title,proposal.rationale,proposal.after||'ready',priority,stamp,stamp);objective=db.prepare('SELECT * FROM objectives WHERE uid=?').get(objectiveUid)}const eventUid=uid(),payload={status:proposal.after,reconciliation:true,source:proposal.source,proposal_fingerprint:fingerprint,before:proposal.before};db.prepare("INSERT OR IGNORE INTO events(uid,project_id,objective_id,kind,actor_kind,actor,assertion,summary,payload,occurred_at,idempotency_key,source) VALUES(?,?,?,'objective.updated','human','Dashboard reviewer','human_judgment',?,?,?,?,?)").run(eventUid,project.id,objective.id,proposal.title,json.write(payload),stamp,`reconciliation:${fingerprint}`,'AI session reconciliation');if(proposal.source.kind==='session')db.prepare(`INSERT INTO external_items(uid,project_id,objective_id,provider,external_id,item_type,title,status,metadata,last_seen_at,created_at,updated_at) VALUES(?,?,?,?,?,'ai_session',?,'linked',?,?,?,?) ON CONFLICT(provider,external_id) DO UPDATE SET project_id=excluded.project_id,objective_id=excluded.objective_id,title=excluded.title,status='linked',metadata=excluded.metadata,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at`).run(`external-${proposal.source.provider}-${digest(proposal.source.id).slice(0,24)}`,project.id,objective.id,proposal.source.provider,proposal.source.id,proposal.source.title,json.write({source_file:proposal.source.source_file,reconciliation:fingerprint}),proposal.observed_at,stamp,stamp)})()
  state.decisions={...(state.decisions||{}),[fingerprint]:decision};state.updated_at=stamp;saveSettings(project,state);return{decision,proposal,workspace:reconciliationWorkspace(project,{sessions:workspace.sessions}),execution:decision==='accepted'}
}
