import { spawn } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { base, json, nowStamp, uid } from './db/index.js'
import { getSpecification, saveSpecification, specificationSourcePacket } from './specification.js'
import { terminalCommand } from './terminal.js'

const jobs=new Map()
const status={type:'string',enum:['closed','ambiguous','open']}
const sourceIds={type:'array',items:{type:'string'},maxItems:40}
const itemSchema={type:'object',additionalProperties:false,required:['title','description','status','source_ids'],properties:{title:{type:'string'},description:{type:'string'},status,source_ids:sourceIds}}
const schema={
  type:'object',additionalProperties:false,
  required:['title','summary','audience','context','scope','non_goals','functional_requirements','quality_requirements','deliverables','acceptance_criteria','constraints','risks','chapters','decisions','open_questions'],
  properties:{
    title:{type:'string'},summary:{type:'string'},audience:{type:'string'},context:{type:'string'},
    scope:{type:'array',items:{type:'string'}},non_goals:{type:'array',items:{type:'string'}},functional_requirements:{type:'array',items:{type:'string'}},quality_requirements:{type:'array',items:{type:'string'}},deliverables:{type:'array',items:{type:'string'}},acceptance_criteria:{type:'array',items:{type:'string'}},constraints:{type:'array',items:{type:'string'}},risks:{type:'array',items:{type:'string'}},
    chapters:{type:'array',minItems:6,maxItems:16,items:{type:'object',additionalProperties:false,required:['key','title','summary','status','source_ids','items'],properties:{key:{type:'string'},title:{type:'string'},summary:{type:'string'},status,source_ids:sourceIds,items:{type:'array',items:itemSchema}}}},
    decisions:{type:'array',items:{type:'object',additionalProperties:false,required:['title','rationale','status','source_ids'],properties:{title:{type:'string'},rationale:{type:'string'},status,source_ids:sourceIds}}},
    open_questions:{type:'array',items:{type:'string'}}
  }
}
const projectRoot=project=>String(project.description||'').match(/Repository:\s*(.+)/i)?.[1]?.trim()||process.cwd()
const cleanModel=value=>{const model=String(value||'').trim();return model&&!model.startsWith('-')&&model.length<=120?model:null}
const cleanEffort=(provider,value)=>{const allowed=provider==='codex'?['low','medium','high','xhigh','max','ultra']:['low','medium','high','xhigh','max'],effort=String(value||'').trim().toLowerCase();return allowed.includes(effort)?effort:null}
const append=(job,chunk)=>{job.log=`${job.log}${String(chunk)}`.slice(-12000);job.updated_at=nowStamp()}
const publicJob=job=>({uid:job.uid,project:job.project,provider:job.provider,model:job.model,effort:job.effort||null,mode:job.mode||'proposal',status:job.status,phase:job.phase,created_at:job.created_at,updated_at:job.updated_at,completed_at:job.completed_at||null,error:job.error||null,log:job.log,result:job.result||null})
const projectBy=value=>base().prepare('SELECT * FROM projects WHERE slug=? OR uid=?').get(value,value)
const analysisKey=project=>`specification-analysis:${project.uid}:latest`
const persistJob=(project,job)=>base().prepare("INSERT INTO management_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(analysisKey(project),json.write({...job,directory:null,packet:null,log:String(job.log||'').slice(-4000)}),nowStamp())
const storedJob=project=>json.read(base().prepare('SELECT value FROM management_settings WHERE key=?').get(analysisKey(project))?.value,null)
const parseClaude=value=>{const envelope=JSON.parse(value),candidate=envelope.structured_output??envelope.result??envelope;if(typeof candidate==='string')return JSON.parse(candidate.replace(/^```json\s*|\s*```$/g,''));return candidate}
const withoutSources=value=>{if(Array.isArray(value))return value.map(withoutSources);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>key!=='source_ids').map(([key,item])=>[key,withoutSources(item)]));return value}
const same=(left,right)=>JSON.stringify(withoutSources(left))===JSON.stringify(withoutSources(right))
const fieldLabels={title:'Titre du GDD',summary:'Résumé exécutif',audience:'Public concerné',context:'Contexte',scope:'Périmètre',non_goals:'Hors périmètre',functional_requirements:'Exigences fonctionnelles',quality_requirements:'Exigences qualité',deliverables:'Livrables',acceptance_criteria:'Critères d’acceptation',constraints:'Contraintes',risks:'Risques',decisions:'Décisions et ambiguïtés',open_questions:'Questions avant validation'}
const proposalFor=(job,current,candidate)=>{const changes=[];for(const [field,title] of Object.entries(fieldLabels)){const before=field==='title'?current.title:current.content[field],after=field==='title'?candidate.title:candidate.content[field];if(!same(before,after))changes.push({id:`field:${field}`,scope:'document',field,kind:'modified',title,before,after})}const currentChapters=new Map((current.content.chapters||[]).map(chapter=>[chapter.key,chapter])),candidateChapters=new Map((candidate.content.chapters||[]).map(chapter=>[chapter.key,chapter]));for(const [key,after] of candidateChapters){const before=currentChapters.get(key);if(!before)changes.push({id:`chapter:${key}`,scope:'chapter',field:'chapters',key,kind:'added',title:after.title,before:null,after,status_before:null,status_after:after.status});else if(!same(before,after))changes.push({id:`chapter:${key}`,scope:'chapter',field:'chapters',key,kind:'modified',title:after.title,before,after,status_before:before.status,status_after:after.status})}for(const [key,before] of currentChapters)if(!candidateChapters.has(key))changes.push({id:`chapter:${key}`,scope:'chapter',field:'chapters',key,kind:'removed',title:before.title,before,after:null,status_before:before.status,status_after:null});return{uid:job.uid,project:job.project,baseline_revision:current.revision,provider:job.provider,model:job.model,effort:job.effort||null,created_at:job.created_at,changes,counts:{total:changes.length,added:changes.filter(item=>item.kind==='added').length,modified:changes.filter(item=>item.kind==='modified').length,removed:changes.filter(item=>item.kind==='removed').length},status:'pending'}}
const remapSources=(currentSources,candidateSources)=>{const sources=[...(currentSources||[])],byIdentity=new Map(sources.map(source=>[`${source.source_file}:${source.source_line}`,source.id])),used=new Set(sources.map(source=>source.id)),idMap=new Map(),next=1;for(const source of candidateSources||[]){const identity=`${source.source_file}:${source.source_line}`,existing=byIdentity.get(identity);if(existing){idMap.set(source.id,existing);continue}while(used.has(`S${next}`))next++;const id=`S${next++}`,added={...source,id};sources.push(added);used.add(id);byIdentity.set(identity,id);idMap.set(source.id,id)}const remap=value=>{if(Array.isArray(value))return value.map(remap);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,key==='source_ids'&&Array.isArray(item)?item.map(id=>idMap.get(id)||id):remap(item)]));return value};return{sources,remap}}
const promptFor=(packet,current=null,mode='proposal')=>`Tu es l'analyste produit principal chargé de ${current?'réévaluer':'reconstruire'} un GDD professionnel depuis des discussions historiques et l'état réel du projet.

Règles impératives :
- Produis un document de décision structuré, pas un journal des conversations ni une simple liste de tâches.
- Crée 6 à 16 chapitres aux titres métier précis : vision, expérience, boucle, narration, monde, systèmes, direction artistique, technique, production, validation, ou des équivalents adaptés au projet.
- Classe chaque chapitre, décision et élément : "closed" seulement si les données indiquent une décision confirmée ou un objectif prouvé ; "ambiguous" si les sources se contredisent ou restent insuffisantes ; "open" si le sujet reste à décider ou à réaliser.
- Cite les identifiants S1, S2… dans source_ids. N'invente jamais de source, de fonctionnalité ou de décision.
- Sépare clairement l'intention durable du projet des instructions d'exécution, règles Git, commandes terminal et détails de session.
- Les critères de validation fournis doivent rester explicites. Les ambiguïtés importantes vont aussi dans open_questions.
- Rédige intégralement en français, de façon concrète et détaillée.
- ${current?'Conserve toute décision encore valide du GDD actuel. Ne change un élément que si une source nouvelle, une contradiction ou une preuve plus forte le justifie.':'Construis le meilleur document initial possible depuis les sources.'}
- ${mode==='audit'?'Mode diagnostic uniquement : identifie précisément les manques, incohérences et corrections recommandées. Orchestrator affichera les écarts sans permettre leur application.':'Mode proposition : produis la meilleure version corrigée afin qu’Orchestrator transforme chaque écart en changement acceptable ou refusable par l’humain.'}
- Retourne uniquement le JSON conforme au schéma demandé.

${current?`GDD ACTUEL À RÉÉVALUER (révision ${current.revision}) :\n${JSON.stringify({title:current.title,...current.content,sources:undefined,question_answers:undefined})}\n\n`:''}DOSSIER DE SOURCES :
${JSON.stringify(packet)}`

export function startSpecificationAnalysis(projectValue,{provider='codex',model=null,effort=null,mode='proposal',limit=500}={}){
  const project=projectBy(projectValue)
  if(!project)throw Object.assign(new Error('Unknown project.'),{status:404})
  provider=String(provider||'').toLowerCase()
  if(!['codex','claude'].includes(provider))throw Object.assign(new Error('Choose Codex or Claude for the analysis.'),{status:400})
  const command=terminalCommand(provider)
  if(!command)throw Object.assign(new Error(`${provider==='codex'?'Codex':'Claude'} is not available on this machine.`),{status:409})
  mode=['audit','proposal'].includes(mode)?mode:'proposal'
  const packet=specificationSourcePacket(project,{limit}),current=getSpecification(project),directory=mkdtempSync(join(tmpdir(),'orchestrator-gdd-')),schemaPath=join(directory,'schema.json'),outputPath=join(directory,'result.json'),selectedModel=cleanModel(model),selectedEffort=cleanEffort(provider,effort),job={uid:uid(),project:project.slug,provider,model:selectedModel,effort:selectedEffort,mode:current.uid?mode:'proposal',status:'running',phase:'Préparation des sources',created_at:nowStamp(),updated_at:nowStamp(),log:'',directory,packet,baseline:current.uid?current:null}
  writeFileSync(schemaPath,JSON.stringify(schema))
  jobs.set(job.uid,job)
  persistJob(project,job)
  const args=provider==='codex'?['exec','--sandbox','read-only','--skip-git-repo-check','--ephemeral','--output-schema',schemaPath,'--output-last-message',outputPath,...(selectedModel?['--model',selectedModel]:[]),...(selectedEffort?['-c',`model_reasoning_effort="${selectedEffort}"`]:[]),'-']:['-p','--safe-mode','--no-session-persistence','--permission-mode','dontAsk','--tools','','--output-format','json','--json-schema',JSON.stringify(schema),...(selectedModel?['--model',selectedModel]:[]),...(selectedEffort?['--effort',selectedEffort]:[])]
  job.phase=`Analyse par ${provider==='codex'?'Codex':'Claude'}`
  const child=spawn(command,args,{cwd:existsSync(projectRoot(project))?projectRoot(project):process.cwd(),env:{...process.env,NO_COLOR:'1'},stdio:['pipe','pipe','pipe']})
  let stdout=''
  child.stdout.on('data',chunk=>{stdout=`${stdout}${chunk}`.slice(-6_000_000);append(job,chunk)})
  child.stderr.on('data',chunk=>append(job,chunk))
  child.stdin.on('error',error=>append(job,`\n${error.message}\n`))
  child.on('error',error=>{job.status='failed';job.phase='Échec du lancement';job.error=error.message;job.completed_at=job.updated_at=nowStamp();persistJob(project,job);rmSync(directory,{recursive:true,force:true})})
  child.on('close',code=>{if(job.status==='failed')return;try{if(code!==0)throw new Error(`${provider==='codex'?'Codex':'Claude'} a terminé avec le code ${code}.`);job.phase='Comparaison avec le GDD actuel';const result=provider==='codex'?JSON.parse(readFileSync(outputPath,'utf8')):parseClaude(stdout),content={...result,status:'draft',generated_at:nowStamp(),generated_from:'ai-conversation-analysis',analysis_provider:provider,analysis_model:selectedModel,generation_stats:packet.stats,sources:packet.sources},candidate={title:result.title||`GDD - ${project.name}`,content};job.candidate=candidate;if(job.baseline){const comparison=proposalFor(job,job.baseline,candidate);if(job.mode==='audit'){job.result={kind:'audit',audit:{...comparison,status:'read-only'}};job.phase=comparison.changes.length?'Diagnostic prêt à consulter':'Aucun écart détecté'}else{job.result={kind:'proposal',proposal:comparison};job.phase=comparison.changes.length?'Proposition prête à examiner':'Aucun changement détecté'}}else{job.result=saveSpecification(project,candidate);job.phase='Brouillon initial prêt pour revue'}job.status='completed';job.completed_at=job.updated_at=nowStamp();persistJob(project,job)}catch(error){job.status='failed';job.phase='Analyse inexploitable';job.error=error.message;job.completed_at=job.updated_at=nowStamp();persistJob(project,job)}finally{rmSync(directory,{recursive:true,force:true})}})
  child.stdin.end(promptFor(packet,job.baseline,job.mode))
  return publicJob(job)
}

export function specificationAnalysisJob(jobUid,projectValue){const project=projectBy(projectValue);if(!project)return null;const job=jobs.get(jobUid)||storedJob(project);if(!job||job.uid!==jobUid||job.project!==project.slug)return null;return publicJob(job)}
export function latestSpecificationAnalysis(projectValue){const project=projectBy(projectValue);if(!project)return null;const running=[...jobs.values()].find(job=>job.project===project.slug&&job.status==='running'),job=running||storedJob(project);return job?publicJob(job):null}
export function reviewSpecificationAnalysis(projectValue,jobUid,input={}){const project=projectBy(projectValue);if(!project)throw Object.assign(new Error('Unknown project.'),{status:404});const job=jobs.get(jobUid)||storedJob(project);if(!job||job.uid!==jobUid||job.project!==project.slug||job.status!=='completed'||job.result?.kind!=='proposal'||!job.candidate)throw Object.assign(new Error('Unknown or incomplete GDD proposal.'),{status:404});if(job.result.proposal.status==='resolved')return{job:publicJob(job),specification:getSpecification(project)};const current=getSpecification(project),proposal=job.result.proposal;if(current.revision!==proposal.baseline_revision)throw Object.assign(new Error('The GDD changed after this analysis. Run a new analysis before merging.'),{status:409});const submitted=input.decisions&&typeof input.decisions==='object'?input.decisions:{},decisions={...(proposal.decisions||{}),...submitted};if(input.finalize===false){job.result.proposal={...proposal,decisions};job.updated_at=nowStamp();persistJob(project,job);jobs.set(job.uid,job);return{job:publicJob(job),specification:current}}const accepted=proposal.changes.filter(change=>decisions[change.id]==='accepted'),pending=proposal.changes.filter(change=>!['accepted','rejected'].includes(decisions[change.id]));if(pending.length)throw Object.assign(new Error('Accept or reject every proposed change before finalizing the review.'),{status:409,pending:pending.map(item=>item.id)});let title=current.title,content={...current.content,chapters:[...(current.content.chapters||[])]};const {sources,remap}=remapSources(current.content.sources,job.candidate.content.sources);for(const change of accepted){if(change.scope==='document'){if(change.field==='title')title=job.candidate.title;else content[change.field]=remap(job.candidate.content[change.field])}else{const index=content.chapters.findIndex(chapter=>chapter.key===change.key);if(change.kind==='removed'){if(index>=0)content.chapters.splice(index,1)}else{const chapter=remap(job.candidate.content.chapters.find(item=>item.key===change.key));if(index>=0)content.chapters[index]=chapter;else content.chapters.push(chapter)}}}if(accepted.length){content={...content,sources,status:'draft',approved_at:null,approved_by:null,generated_at:nowStamp(),generated_from:'ai-merge-review',analysis_provider:job.provider,analysis_model:job.model};content.question_answers=(content.question_answers||[]).filter(answer=>(content.open_questions||[]).includes(answer.question))}const specification=accepted.length?saveSpecification(project,{title,content}):current;job.result.proposal={...proposal,status:'resolved',resolved_at:nowStamp(),decisions,accepted:accepted.length,rejected:proposal.changes.length-accepted.length,applied_revision:specification.revision};job.updated_at=nowStamp();persistJob(project,job);jobs.set(job.uid,job);return{job:publicJob(job),specification}}
