import { base, json } from './db/index.js'

export function deriveProjectState(projectId) {
  const objectives=base().prepare(`SELECT o.*,(SELECT count(*) FROM events e WHERE e.objective_id=o.id) event_count,(SELECT count(*) FROM evidence_manifests e WHERE e.objective_id=o.id) evidence_count,(SELECT max(e.occurred_at) FROM events e WHERE e.objective_id=o.id) last_activity,(SELECT count(*) FROM objective_dependencies d WHERE d.objective_id=o.id) dependency_count,(SELECT count(*) FROM objective_dependencies d JOIN objectives prerequisite ON prerequisite.id=d.depends_on_id WHERE d.objective_id=o.id AND prerequisite.status!='proven') unmet_dependencies FROM objectives o WHERE o.project_id=? ORDER BY o.priority,o.id`).all(projectId)
  const events=base().prepare("SELECT id,uid,objective_id,kind,summary,payload,occurred_at FROM events WHERE project_id=? AND objective_id IS NOT NULL ORDER BY id").all(projectId).map(row=>({...row,payload:json.read(row.payload,{})}))
  const blockers=base().prepare("SELECT * FROM blockers WHERE project_id=? AND status='open' ORDER BY created_at DESC").all(projectId)
  const derived=objectives.map(objective=>{
    const history=events.filter(event=>event.objective_id===objective.id),latestRequest=[...history].reverse().find(event=>event.kind==='human_judgment.requested'),latestProven=[...history].reverse().find(event=>event.kind==='objective.updated'&&event.payload.status==='proven'),latestSatisfaction=[...history].reverse().find(event=>['verdict.recorded','human_judgment.cancelled'].includes(event.kind)||event.kind==='objective.updated'&&event.payload.status==='proven'),openBlockers=blockers.filter(blocker=>blocker.objective_id===objective.id&&blocker.title!=='human_request'&&(!latestProven||blocker.event_id>latestProven.id)),legacyRequest=blockers.find(blocker=>blocker.objective_id===objective.id&&blocker.title==='human_request'&&(!latestProven||blocker.event_id>latestProven.id)),explicit=objective.status,staleBlocked=explicit==='blocked'&&!openBlockers.length,effective=explicit==='proven'?'proven':openBlockers.length?'blocked':staleBlocked?'ready':explicit,judgmentRequested=effective!=='proven'&&Boolean(latestRequest&&(!latestSatisfaction||latestSatisfaction.id<latestRequest.id)||legacyRequest&&!latestSatisfaction),wasProven=Boolean(latestProven),reopened=effective!=='proven'&&wasProven
    return{...objective,stored_status:explicit,status:effective,status_reason:openBlockers.length?'active_blocker':staleBlocked?'stale_blocker_cleared':null,feasible:!['proven','abandoned','blocked'].includes(effective)&&objective.unmet_dependencies===0,open_blocker_count:effective==='proven'?0:openBlockers.length,judgment_requested:judgmentRequested,reopened,judgment_request:judgmentRequested?latestRequest?{uid:latestRequest.uid,objective_id:objective.id,summary:latestRequest.summary,occurred_at:latestRequest.occurred_at}:{uid:`legacy-blocker-${legacyRequest.id}`,objective_id:objective.id,summary:legacyRequest.detail||'Human judgment requested',occurred_at:legacyRequest.created_at}:null}
  })
  const ids=new Set(derived.filter(row=>row.status!=='proven').map(row=>row.id)),activeBlockers=blockers.filter(blocker=>{if(blocker.title==='human_request'||!ids.has(blocker.objective_id))return false;const latestProven=[...events].reverse().find(event=>event.objective_id===blocker.objective_id&&event.kind==='objective.updated'&&event.payload.status==='proven');return!latestProven||blocker.event_id>latestProven.id})
  return{objectives:derived,blockers:activeBlockers,judgmentRequests:derived.map(row=>row.judgment_request).filter(Boolean)}
}

export function deriveCoordination(projectId,timeoutMinutes=15){
  const rows=base().prepare("SELECT * FROM events WHERE project_id=? AND kind IN ('work.started','work.heartbeat','work.finished','git.state') ORDER BY occurred_at,id").all(projectId).map(row=>({...row,payload:json.read(row.payload,{})})),gitRows=rows.filter(row=>row.kind==='git.state'),latestGit=gitRows.at(-1)||null,sessions=new Map()
  for(const row of rows.filter(row=>row.kind.startsWith('work.'))){const id=row.payload.session_id;if(!id)continue;const state=sessions.get(id)||{session_id:id,start:null,heartbeat:null,finish:null};if(row.kind==='work.started')state.start=row;if(row.kind==='work.heartbeat')state.heartbeat=row;if(row.kind==='work.finished')state.finish=row;sessions.set(id,state)}
  const now=Date.now(),timeoutMs=Math.max(60_000,Number(timeoutMinutes||15)*60_000),pathOverlap=(a,b)=>{const x=String(a).replace(/\/$/,'')+'/',y=String(b).replace(/\/$/,'')+'/';return x.startsWith(y)||y.startsWith(x)},passes=[...sessions.values()].filter(state=>state.start).map(state=>{const last=state.finish||state.heartbeat||state.start,data=state.start.payload,branchGit=[...gitRows].reverse().find(row=>row.payload.branch===data.branch),finished=Boolean(state.finish),abandoned=!finished&&now-new Date(last.occurred_at).getTime()>timeoutMs,stale=!finished&&Boolean(branchGit?.payload.head_commit&&data.base_commit&&branchGit.payload.head_commit!==data.base_commit);return{session_id:state.session_id,machine:data.machine,branch:data.branch,base_commit:data.base_commit,paths:data.paths||[],summary:state.start.summary,started_at:state.start.occurred_at,last_seen_at:last.occurred_at,finished_at:state.finish?.occurred_at||null,outcome:state.finish?.payload.outcome||null,status:finished?'finished':abandoned?'abandoned':stale?'stale':'active',stale,abandoned,dirty:Boolean(branchGit?.payload.dirty),head_commit:branchGit?.payload.head_commit||null,overlaps:[]}}),live=passes.filter(pass=>!['finished','abandoned'].includes(pass.status))
  for(const pass of live)pass.overlaps=live.filter(other=>other.session_id!==pass.session_id&&pass.paths.some(path=>other.paths.some(otherPath=>pathOverlap(path,otherPath)))).map(other=>other.session_id)
  return{protocol:{version:1,heartbeat_timeout_minutes:timeoutMs/60_000},latest_git:latestGit?{...latestGit.payload,observed_at:latestGit.occurred_at}:null,active:live,recent:passes.sort((a,b)=>b.started_at.localeCompare(a.started_at)).slice(0,30),counts:{active:live.filter(x=>x.status==='active').length,stale:live.filter(x=>x.stale).length,conflicts:live.filter(x=>x.overlaps.length).length,abandoned:passes.filter(x=>x.abandoned).length}}
}

export function deriveGitGuard(projectId,{machine=null,branch=null,baseCommit=null}={}){
  const rows=base().prepare("SELECT payload,occurred_at FROM events WHERE project_id=? AND kind='git.state' ORDER BY occurred_at DESC,id DESC").all(projectId).map(row=>({...row,payload:json.read(row.payload,{})})),latest=rows[0]||null,branchRows=branch?rows.filter(row=>row.payload.branch===branch):rows,local=machine?rows.find(row=>row.payload.machine===machine&&(!branch||row.payload.branch===branch)):branchRows[0]||latest,reference=branchRows.find(row=>machine&&row.payload.machine!==machine)||branchRows[0]||latest,current=baseCommit||local?.payload.head_commit||null,expected=reference?.payload.head_commit||null,status=!expected?'unknown':!current?'needs-local-state':current===expected?(local?.payload.dirty?'dirty':'current'):'divergent'
  return{safe_to_start:status==='current',status,machine:machine||local?.payload.machine||null,branch:branch||local?.payload.branch||reference?.payload.branch||null,current_commit:current,expected_commit:expected,dirty:Boolean(local?.payload.dirty),reference_machine:reference?.payload.machine||null,reference_observed_at:reference?.occurred_at||null,required_action:status==='current'?null:status==='dirty'?'Commit, stash, or explicitly scope the dirty files before starting.':status==='divergent'?'Fetch the remote, compare branches, and rebase or merge before starting.':'Record the local Git state before starting.',execution:false}
}

export function deriveConfidence(projectId){
  const state=deriveProjectState(projectId),coordination=deriveCoordination(projectId),evidence=base().prepare("SELECT count(*) total,sum(CASE WHEN status='available' AND sha256 IS NOT NULL THEN 1 ELSE 0 END) trusted FROM evidence_manifests WHERE project_id=?").get(projectId),latestEvent=base().prepare('SELECT occurred_at FROM events WHERE project_id=? ORDER BY occurred_at DESC,id DESC LIMIT 1').get(projectId),latestGit=coordination.latest_git,ageHours=(value)=>value?Math.max(0,(Date.now()-new Date(value).getTime())/3600000):Infinity,coverage=evidence.total?evidence.trusted/evidence.total:0,penalties={evidence:Math.round((1-coverage)*30),blockers:Math.min(30,state.blockers.length*15),judgments:Math.min(20,state.judgmentRequests.length*10),coordination:Math.min(25,coordination.counts.conflicts*10+coordination.counts.stale*10),git:!latestGit?15:(ageHours(latestGit.observed_at)>48?10:0)+(latestGit.dirty?5:0),freshness:ageHours(latestEvent?.occurred_at)>168?20:ageHours(latestEvent?.occurred_at)>48?10:0},score=Math.max(0,100-Object.values(penalties).reduce((sum,value)=>sum+value,0)),label=score>=80?'high':score>=55?'medium':'low'
  return{score,label,generated_at:new Date().toISOString(),components:{evidence:{score:100-penalties.evidence,coverage:Math.round(coverage*100),trusted:evidence.trusted||0,total:evidence.total||0},blockers:{score:100-penalties.blockers,active:state.blockers.length},judgments:{score:100-penalties.judgments,pending:state.judgmentRequests.length},coordination:{score:100-penalties.coordination,conflicts:coordination.counts.conflicts,stale:coordination.counts.stale},git:{score:100-penalties.git,reported:Boolean(latestGit),dirty:Boolean(latestGit?.dirty),observed_at:latestGit?.observed_at||null},freshness:{score:100-penalties.freshness,last_activity:latestEvent?.occurred_at||null}},penalties}
}
