import { base, json } from './db/index.js'

export function deriveProjectState(projectId) {
  const objectives=base().prepare(`SELECT o.*,(SELECT count(*) FROM events e WHERE e.objective_id=o.id) event_count,(SELECT count(*) FROM evidence_manifests e WHERE e.objective_id=o.id) evidence_count,(SELECT max(e.occurred_at) FROM events e WHERE e.objective_id=o.id) last_activity FROM objectives o WHERE o.project_id=? ORDER BY o.priority,o.id`).all(projectId)
  const events=base().prepare("SELECT id,uid,objective_id,kind,summary,payload,occurred_at FROM events WHERE project_id=? AND objective_id IS NOT NULL ORDER BY id").all(projectId).map(row=>({...row,payload:json.read(row.payload,{})}))
  const blockers=base().prepare("SELECT * FROM blockers WHERE project_id=? AND status='open' ORDER BY created_at DESC").all(projectId)
  const derived=objectives.map(objective=>{
    const history=events.filter(event=>event.objective_id===objective.id),latestRequest=[...history].reverse().find(event=>event.kind==='human_judgment.requested'),latestProven=[...history].reverse().find(event=>event.kind==='objective.updated'&&event.payload.status==='proven'),latestSatisfaction=[...history].reverse().find(event=>['verdict.recorded','human_judgment.cancelled'].includes(event.kind)||event.kind==='objective.updated'&&event.payload.status==='proven'),openBlockers=blockers.filter(blocker=>blocker.objective_id===objective.id&&blocker.title!=='human_request'&&(!latestProven||blocker.event_id>latestProven.id)),legacyRequest=blockers.find(blocker=>blocker.objective_id===objective.id&&blocker.title==='human_request'&&(!latestProven||blocker.event_id>latestProven.id)),explicit=objective.status,effective=explicit==='proven'?'proven':openBlockers.length?'blocked':explicit,judgmentRequested=effective!=='proven'&&Boolean(latestRequest&&(!latestSatisfaction||latestSatisfaction.id<latestRequest.id)||legacyRequest&&!latestSatisfaction),wasProven=Boolean(latestProven),reopened=effective!=='proven'&&wasProven
    return{...objective,stored_status:explicit,status:effective,open_blocker_count:effective==='proven'?0:openBlockers.length,judgment_requested:judgmentRequested,reopened,judgment_request:judgmentRequested?latestRequest?{uid:latestRequest.uid,objective_id:objective.id,summary:latestRequest.summary,occurred_at:latestRequest.occurred_at}:{uid:`legacy-blocker-${legacyRequest.id}`,objective_id:objective.id,summary:legacyRequest.detail||'Human judgment requested',occurred_at:legacyRequest.created_at}:null}
  })
  const ids=new Set(derived.filter(row=>row.status!=='proven').map(row=>row.id)),activeBlockers=blockers.filter(blocker=>{if(blocker.title==='human_request'||!ids.has(blocker.objective_id))return false;const latestProven=[...events].reverse().find(event=>event.objective_id===blocker.objective_id&&event.kind==='objective.updated'&&event.payload.status==='proven');return!latestProven||blocker.event_id>latestProven.id})
  return{objectives:derived,blockers:activeBlockers,judgmentRequests:derived.map(row=>row.judgment_request).filter(Boolean)}
}
