import { createSign, createHash } from 'node:crypto'
import { readFileSync, statSync } from 'node:fs'
import { basename, extname } from 'node:path'
import { refreshAccess, PROVIDER_OF } from './oauth.js'

/**
 * Uploads proofs to a remote storage, so a teammate can read them without
 * having the repository.
 *
 * Two ways to authenticate, and the order matters:
 *
 * 1. **The connected account** (an OAuth refresh token). This is the normal
 *    path: everyone authorises THEIR account, the files land in THEIR space, and
 *    the tool never needs anybody else's account.
 * 2. **A Google service account**, as a last resort. It asks for no
 *    authorisation, but it has NO Drive quota at all: it can create a folder and
 *    can never put a file in it. Kept for Workspace shared drives, where the
 *    quota comes from the organisation.
 *
 * The argument that ruled OAuth out at first was wrong: you authorise once, we
 * keep the token, and nobody intervenes again.
 */

const MIMES = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.md': 'text/markdown',
  '.json': 'application/json',
  '.csv': 'text/csv',
  '.txt': 'text/plain',
}

const mimeOf = (path) => MIMES[extname(path).toLowerCase()] ?? 'application/octet-stream'

export const fileFingerprint = (path) =>
  createHash('sha256').update(readFileSync(path)).digest('hex')

// ---- Google Drive ---------------------------------------------------------

const base64url = (b) => Buffer.from(b).toString('base64url')

/**
 * An access token signed locally from the service-account key. No library, no
 * redirect: we sign a JWT and exchange it.
 */
async function serviceAccountToken(key) {
  const nowStamp = Math.floor(Date.now() / 1000)
  const jwtHeader = base64url(JSON.stringify({ alg: 'RS256', typ: 'JWT' }))
  const body = base64url(
    JSON.stringify({
      iss: key.client_email,
      scope: 'https://www.googleapis.com/auth/drive.file',
      aud: 'https://oauth2.googleapis.com/token',
      iat: nowStamp,
      exp: nowStamp + 3600,
    }),
  )

  const signature = createSign('RSA-SHA256').update(`${jwtHeader}.${body}`).sign(key.private_key, 'base64url')

  const res = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      assertion: `${jwtHeader}.${body}.${signature}`,
    }),
  })

  const d = await res.json().catch(() => ({}))
  if (!res.ok || !d.access_token) {
    throw new Error(
      `Google refuses the service-account key: ${d.error_description ?? d.error ?? res.status}`,
    )
  }
  return d.access_token
}

/** A storage's credentials, whatever shape they were stored in. */
const credentialsOf = (storage) =>
  typeof storage.credentials === 'string' ? JSON.parse(storage.credentials) : (storage.credentials ?? null)

/**
 * A valid access token, without caring how. This is the only place that knows
 * about both paths: everywhere else deals with "a token".
 */
export async function tokenFor(storage) {
  const id = credentialsOf(storage)
  if (!id) throw new Error('No credentials recorded for this storage.')

  if (id.refresh_token) return refreshAccess(PROVIDER_OF[storage.provider], id.refresh_token)
  if (id.client_email && id.private_key) return serviceAccountToken(id)
  // A Dropbox app token, generated by hand in the console. It does not expire,
  // but it belongs to exactly one person.
  if (id.token) return id.token

  throw new Error(
    'The credentials look like neither a connected account, nor a service-account key, ' +
      'nor an app token.',
  )
}

/** A service account can deposit nothing: say it once, here. */
const isServiceAccount = (storage) => {
  const id = credentialsOf(storage)
  return Boolean(id?.client_email && !id?.refresh_token)
}

/**
 * Creates the drop folder. With a connected account it is born directly in the
 * person's Drive, and there is nothing to share and nothing to paste by hand.
 */
export async function createDriveFolder(storage, { name = 'Orchestrator — Proofs', shareWith = null } = {}) {
  const token = await tokenFor(storage)
  const key = credentialsOf(storage)

  const res = await fetch('https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: name, mimeType: 'application/vnd.google-apps.folder' }),
  })

  const d = await res.json().catch(() => ({}))
  if (!res.ok || !d.id) {
    throw new Error(`Drive refuses to create the folder: ${d.error?.message ?? res.status}`)
  }

  // With a service account, without this share the folder stays invisible: it
  // belongs to an identity that has no interface. With a connected account the
  // folder is already in the person's Drive — sharing then opens access to a
  // teammate. A failure here cancels nothing.
  let sharedWith = null
  if (shareWith) {
    const r = await fetch(
      `https://www.googleapis.com/drive/v3/files/${d.id}/permissions?sendNotificationEmail=false`,
      {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ role: 'writer', type: 'user', emailAddress: shareWith }),
      },
    )
    const rd = await r.json().catch(() => ({}))
    sharedWith = r.ok ? shareWith : `share failed: ${rd.error?.message ?? r.status}`
  }

  // A folder consumes no quota, a file does. Without this probe we handed back a
  // folder marked "ready" that nothing could ever enter — verified:
  // `storageQuotaExceeded` on the first upload. So we test right away, and clean
  // up after ourselves rather than leaving a trap.
  const probe = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',
    {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'multipart/related; boundary=probe' },
      body:
        `--probe\r\nContent-Type: application/json\r\n\r\n` +
        JSON.stringify({ name: '.orchestrator-probe', parents: [d.id] }) +
        `\r\n--probe\r\nContent-Type: text/plain\r\n\r\nok\r\n--probe--\r\n`,
    },
  )
  const sd = await probe.json().catch(() => ({}))

  if (!probe.ok) {
    await fetch(`https://www.googleapis.com/drive/v3/files/${d.id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    }).catch(() => {})

    const m = sd.error?.message ?? String(probe.status)
    throw new Error(
      /quota/i.test(m) && isServiceAccount(storage)
        ? 'A service account has no Drive quota: it can create a folder, never put a file in it. ' +
          'Click "Connect" to authorise your own account — the proofs will go into your Drive. ' +
          `Or, if you want to keep the service account (${key.client_email}), it needs a Workspace ` +
          'shared drive, whose quota comes from the organisation.'
        : `Drive refuses to write into the folder it created: ${m}`,
    )
  }

  if (sd.id) {
    await fetch(`https://www.googleapis.com/drive/v3/files/${sd.id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    }).catch(() => {})
  }

  return { id: d.id, name: d.name, url: d.webViewLink, sharedWith }
}

async function uploadToDrive(storage, path) {
  const { target } = storage
  if (!target) {
    throw new Error('No Drive folder targeted — run "prepare the folder" before uploading.')
  }

  const token = await tokenFor(storage)
  const bytes = readFileSync(path)
  const limite = `----orchestrator${Date.now()}`

  const body = Buffer.concat([
    Buffer.from(
      `--${limite}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n` +
        JSON.stringify({ name: basename(path), parents: [target] }) +
        `\r\n--${limite}\r\nContent-Type: ${mimeOf(path)}\r\n\r\n`,
    ),
    bytes,
    Buffer.from(`\r\n--${limite}--\r\n`),
  ])

  const res = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink&supportsAllDrives=true',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': `multipart/related; boundary=${limite}`,
      },
      body: body,
    },
  )

  const d = await res.json().catch(() => ({}))
  if (!res.ok || !d.id) {
    const m = d.error?.message ?? String(res.status)
    // La panne attendue avec un compte de service : il n'a pas de quota propre.
    // Say so, rather than handing back a raw code nobody can read.
    if (/quota/i.test(m) && isServiceAccount(storage)) {
      throw new Error(
        'The service account has no Drive storage quota: it will never be able to deposit a file. ' +
          'Connect an account from the Storage screen, or target a Workspace shared drive.',
      )
    }
    throw new Error(`Drive refuses the upload: ${m}`)
  }

  return { remote_id: d.id, remote_url: d.webViewLink ?? `https://drive.google.com/file/d/${d.id}/view` }
}

// ---- Dropbox --------------------------------------------------------------

async function uploadToDropbox(storage, path) {
  const token = await tokenFor(storage)
  const folder = (storage.target ?? '/Orchestrator').replace(/\/+$/, '')
  const remotePath = `${folder}/${basename(path)}`

  const res = await fetch('https://content.dropboxapi.com/2/files/upload', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/octet-stream',
      // `overwrite` and not `add`: uploading the same proof twice must not create
      // "file (1)", "file (2)" and turn the folder unreadable.
      'Dropbox-API-Arg': JSON.stringify({ path: remotePath, mode: 'overwrite', mute: true }),
    },
    body: readFileSync(path),
  })

  const d = await res.json().catch(() => ({}))
  if (!res.ok || !d.id) {
    throw new Error(`Dropbox refuses the upload: ${d.error_summary ?? res.status}`)
  }

  // A shareable link, if it is allowed. We do not fail when it is not: the file
  // is deposited, and that is what matters.
  let url = null
  try {
    const l = await fetch('https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings', {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ path: d.path_lower }),
    })
    const dl = await l.json().catch(() => ({}))
    url = dl.url ?? dl.error?.shared_link_already_exists?.metadata?.url ?? null
  } catch {
    /* the link is a convenience, not the proof */
  }

  return { remote_id: d.id, remote_url: url }
}

// ---- surface commune ------------------------------------------------------

const DRIVERS = { gdrive: uploadToDrive, dropbox: uploadToDropbox }

export async function upload(storage, path) {
  const driver = DRIVERS[storage.provider]
  if (!driver) throw new Error(`Unknown storage: ${storage.provider}`)

  const st = statSync(path)
  if (!st.isFile()) throw new Error(`Not a file: ${path}`)
  if (st.size > 100 * 1024 * 1024) {
    throw new Error(`${basename(path)} weighs ${Math.round(st.size / 1048576)} MB — past 100 MB we do not upload it.`)
  }

  const r = await driver(storage, path)
  return { ...r, bytes: st.size, sha256: fileFingerprint(path) }
}

/** A check that deposits nothing: does the storage answer, and where? */
export async function checkStorage(storage) {
  const token = await tokenFor(storage)

  if (storage.provider === 'gdrive') {
    const key = credentialsOf(storage)
    if (!storage.target) {
      return {
        status: 'refused',
        detail: isServiceAccount(storage)
          ? `Key valid, but no folder targeted. Share a folder with ${key.client_email}.`
          : 'Account valid, but no folder targeted — run "prepare the folder".',
      }
    }
    const res = await fetch(
      `https://www.googleapis.com/drive/v3/files/${storage.target}?fields=id,name&supportsAllDrives=true`,
      { headers: { Authorization: `Bearer ${token}` } },
    )
    const d = await res.json().catch(() => ({}))
    return res.ok
      ? { status: 'ok', detail: `folder “${d.name}” reachable` }
      : {
          status: 'refused',
          detail:
            d.error?.message?.includes('not found')
              ? isServiceAccount(storage)
                ? `Folder not found — did you share it with ${key.client_email}?`
                : 'Folder not found: it was deleted, or it belongs to an account other than the connected one.'
              : (d.error?.message ?? `error ${res.status}`),
        }
  }

  const res = await fetch('https://api.dropboxapi.com/2/users/get_current_account', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}` },
  })
  const d = await res.json().catch(() => ({}))
  return res.ok
    ? { status: 'ok', detail: `account ${d.email ?? d.name?.display_name ?? 'connected'}` }
    : { status: 'refused', detail: d.error_summary ?? `error ${res.status}` }
}
