import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { decrypt } from './crypto.js'

const apps=()=>JSON.parse(readFileSync(join(homedir(),'.orchestrator','oauth.json'),'utf8'))
const digest=(value)=>createHash('sha256').update(value).digest('hex')
const prefix='orchestrator-journal--'
async function token(connection){const credentials=JSON.parse(decrypt(connection.credentials)||'{}'),app=apps()[connection.provider==='gdrive'?'google':'dropbox'];if(!credentials.refresh_token||!app)throw new Error('Stored OAuth connection is incomplete.');const url=connection.provider==='gdrive'?'https://oauth2.googleapis.com/token':'https://api.dropboxapi.com/oauth2/token';const response=await fetch(url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:credentials.refresh_token,client_id:app.client_id,client_secret:app.client_secret})});const data=await response.json();if(!response.ok||!data.access_token)throw new Error(`${connection.label} token refresh failed (${response.status}).`);return data.access_token}
export function journalName(machine,cursor,body){return `${prefix}${machine}--${String(cursor).padStart(12,'0')}--${digest(body).slice(0,16)}.json`}
async function driveList(connection,access){const q=`name contains '${prefix}' and '${connection.target}' in parents and trashed=false`;const response=await fetch(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&pageSize=1000&fields=files(id,name,size,md5Checksum)`,{headers:{Authorization:`Bearer ${access}`}});const data=await response.json();if(!response.ok)throw new Error(`Drive journal listing failed (${response.status}).`);return(data.files||[]).map(file=>({name:file.name,id:file.id}))}
async function dropboxList(access){const entries=[];let response=await fetch('https://api.dropboxapi.com/2/files/list_folder',{method:'POST',headers:{Authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({path:'/orchestrator-memory/journals'})});if(response.status===409)return entries;while(true){const data=await response.json();if(!response.ok)throw new Error(`Dropbox journal listing failed (${response.status}).`);entries.push(...(data.entries||[]).filter(row=>row['.tag']==='file'&&row.name.startsWith(prefix)).map(row=>({name:row.name,id:row.path_lower})));if(!data.has_more)break;response=await fetch('https://api.dropboxapi.com/2/files/list_folder/continue',{method:'POST',headers:{Authorization:`Bearer ${access}`,'content-type':'application/json'},body:JSON.stringify({cursor:data.cursor})})}return entries}
export async function listJournals(connection){const access=await token(connection);return{access,files:connection.provider==='gdrive'?await driveList(connection,access):await dropboxList(access)}}
export async function downloadJournal(connection,access,file){const response=connection.provider==='gdrive'?await fetch(`https://www.googleapis.com/drive/v3/files/${file.id}?alt=media`,{headers:{Authorization:`Bearer ${access}`}}):await fetch('https://content.dropboxapi.com/2/files/download',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Dropbox-API-Arg':JSON.stringify({path:file.id})}});if(!response.ok)throw new Error(`${connection.label} journal download failed (${response.status}).`);const body=await response.text();return{body,bundle:JSON.parse(body),sha256:digest(body)}}
export async function uploadJournal(connection,access,name,body){if(connection.provider==='gdrive'){const metadata={name,parents:[connection.target],mimeType:'application/json',appProperties:{orchestratorJournal:'true'}};const form=new FormData();form.append('metadata',new Blob([JSON.stringify(metadata)],{type:'application/json'}));form.append('file',new Blob([body],{type:'application/json'}));const response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{Authorization:`Bearer ${access}`},body:form});const data=await response.json();if(!response.ok)throw new Error(`Drive journal upload failed (${response.status}).`);return data.id}const path=`/orchestrator-memory/journals/${name}`;const response=await fetch('https://content.dropboxapi.com/2/files/upload',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Dropbox-API-Arg':JSON.stringify({path,mode:'add',autorename:false}),'content-type':'application/octet-stream'},body});if(!response.ok)throw new Error(`Dropbox journal upload failed (${response.status}).`);return path}
export const journalDigest=digest
