import { closeSync, existsSync, mkdirSync, openSync, readFileSync, readSync, realpathSync, readdirSync, statSync, watch, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { basename, delimiter, dirname, extname, isAbsolute, join, relative } from 'node:path'
import { createHash, randomBytes } from 'node:crypto'
import { spawn } from 'node-pty'
import { WebSocketServer } from 'ws'
import { routeAiProvider } from './ai-usage.js'
import { base, dbPath, json, nowStamp, uid } from './db/index.js'
import { permissionProfiles, resolvePermissionOptions } from './permission-profiles.js'

const sessions=new Map()
const exitListeners=new Set()
const checkpointListeners=new Set()
const commandCandidates={
  codex:['codex','/Applications/ChatGPT.app/Contents/Resources/codex'],
  claude:['claude','/Users/macbook/.local/bin/claude'],
  gemini:['gemini'],
  opencode:['opencode'],
  copilot:['copilot'],
}
const providerLabels={codex:'Codex',claude:'Claude',gemini:'Gemini',opencode:'OpenCode',copilot:'GitHub Copilot'}
const envCommands={codex:'ORCHESTRATOR_CODEX_COMMAND',claude:'ORCHESTRATOR_CLAUDE_COMMAND',gemini:'ORCHESTRATOR_GEMINI_COMMAND',opencode:'ORCHESTRATOR_OPENCODE_COMMAND',copilot:'ORCHESTRATOR_COPILOT_COMMAND'}
const effortLevels={codex:['low','medium','high','xhigh','max','ultra'],claude:['low','medium','high','xhigh','max'],gemini:[],opencode:[],copilot:[]}
let modelCache={at:0,value:null}
const nativeTranscriptCache=new Map()
const tailText=(path,max=512*1024)=>{const stat=statSync(path),length=Math.min(stat.size,max),fd=openSync(path,'r'),buffer=Buffer.alloc(length);try{return buffer.subarray(0,readSync(fd,buffer,0,length,Math.max(0,stat.size-length))).toString('utf8')}finally{closeSync(fd)}}
const recentJsonl=root=>{try{return readdirSync(root,{recursive:true,withFileTypes:true}).filter(entry=>entry.isFile()&&entry.name.endsWith('.jsonl')).map(entry=>join(entry.parentPath||entry.path,entry.name)).map(path=>({path,mtime:statSync(path).mtimeMs})).sort((a,b)=>b.mtime-a.mtime).slice(0,80).map(item=>item.path)}catch{return[]}}
const headText=(path,max=128*1024)=>{const fd=openSync(path,'r'),buffer=Buffer.alloc(max);try{return buffer.subarray(0,readSync(fd,buffer,0,max,0)).toString('utf8')}finally{closeSync(fd)}}
const configuredModels=()=>{const models=Object.fromEntries(Object.keys(commandCandidates).map(id=>[id,null])),efforts=Object.fromEntries(Object.keys(commandCandidates).map(id=>[id,null]));try{const config=readFileSync(join(homedir(),'.codex','config.toml'),'utf8');models.codex=config.match(/^model\s*=\s*["']([^"']+)["']/m)?.[1]||null;efforts.codex=config.match(/^model_reasoning_effort\s*=\s*["']([^"']+)["']/m)?.[1]||null}catch{}try{const settings=JSON.parse(readFileSync(join(homedir(),'.claude','settings.json'),'utf8'));models.claude=typeof settings.model==='string'?settings.model:null;efforts.claude=typeof settings.effort==='string'?settings.effort:null}catch{}return{models,efforts}}
export function detectedProviderModels(){if(modelCache.value&&Date.now()-modelCache.at<60000)return modelCache.value;const configured=configuredModels(),found=Object.fromEntries(Object.keys(commandCandidates).map(id=>[id,new Map()])),add=(provider,id,source)=>{id=String(id||'').trim();if(!found[provider]||!id||id==='unknown'||/^<.*>$/.test(id)||id.length>120)return;const current=found[provider].get(id);found[provider].set(id,{id,label:id,source:current?.source==='configured'?'configured':source,configured:source==='configured'||Boolean(current?.configured)})};add('codex',configured.models.codex,'configured');add('claude',configured.models.claude,'configured');for(const path of recentJsonl(join(homedir(),'.codex','sessions')))for(const match of tailText(path).matchAll(/"model"\s*:\s*"([^"\\]{2,120})"/g))add('codex',match[1],'observed');for(const root of [join(homedir(),'.codex','archived_sessions')])for(const path of recentJsonl(root).slice(0,20))for(const match of tailText(path).matchAll(/"model"\s*:\s*"([^"\\]{2,120})"/g))add('codex',match[1],'observed');for(const path of recentJsonl(join(homedir(),'.claude','projects')))for(const match of tailText(path).matchAll(/"model"\s*:\s*"([^"\\]{2,120})"/g))add('claude',match[1],'observed');const value=Object.fromEntries(Object.keys(commandCandidates).map(id=>[id,{models:[...found[id].values()],default_model:configured.models[id],efforts:effortLevels[id],default_effort:effortLevels[id].includes(configured.efforts[id])?configured.efforts[id]:id==='claude'?'high':effortLevels[id][0]||null}]));modelCache={at:Date.now(),value};return value}
const executable=name=>{const configured=process.env[envCommands[name]];if(configured&&existsSync(configured))return configured;for(const candidate of commandCandidates[name]){if(candidate.includes('/')&&existsSync(candidate))return candidate;for(const directory of String(process.env.PATH||'').split(delimiter))if(directory&&existsSync(join(directory,candidate)))return join(directory,candidate)}return null}
export const terminalCommand=provider=>executable(String(provider||'').toLowerCase())
const optionValue=(value,max=160)=>{const normalized=String(value||'').trim();if(!normalized||normalized.startsWith('-')||normalized.length>max||/[\r\n\0]/.test(normalized))return null;return normalized}
const promptValue=(value,max=10000)=>{const normalized=String(value||'').trim();if(!normalized||normalized.startsWith('-')||normalized.length>max||normalized.includes('\0'))return null;return normalized}
export function terminalArguments(provider,input={}){
  const resume=['new','last','picker','id'].includes(input.resume_mode)?input.resume_mode:'new',resumeId=optionValue(input.resume_id),model=optionValue(input.model),prompt=promptValue(input.prompt),dangerous=Boolean(input.dangerously_bypass),effort=effortLevels[provider]?.includes(input.effort)?input.effort:null,args=[]
  if(provider==='codex'){
    if(resume!=='new'){args.push('resume');if(resume==='last')args.push('--last');if(resume==='id'){if(!resumeId)throw new Error('A valid Codex session ID or name is required.');args.push(resumeId)}}
    if(model)args.push('--model',model)
    if(effort)args.push('-c',`model_reasoning_effort="${effort}"`)
    if(dangerous)args.push('--dangerously-bypass-approvals-and-sandbox')
    else{const sandbox=['read-only','workspace-write','danger-full-access'].includes(input.sandbox)?input.sandbox:null,approval=['untrusted','on-request','never'].includes(input.approval_policy)?input.approval_policy:null;if(sandbox)args.push('--sandbox',sandbox);if(approval)args.push('--ask-for-approval',approval)}
    if(input.search)args.push('--search')
    args.push('--no-alt-screen')
  }else if(provider==='claude'){
    if(resume==='last')args.push('--continue');if(resume==='picker')args.push('--resume');if(resume==='id'){if(!resumeId)throw new Error('A valid Claude session ID is required.');args.push('--resume',resumeId)}
    if(model)args.push('--model',model)
    if(dangerous)args.push('--dangerously-skip-permissions')
    else if(['acceptEdits','auto','manual','dontAsk','plan'].includes(input.permission_mode))args.push('--permission-mode',input.permission_mode)
    if(effort)args.push('--effort',effort)
    if(input.disable_tools)args.push('--tools','','--mcp-config','{"mcpServers":{}}','--strict-mcp-config','--safe-mode')
    if(input.fork_session&&resume!=='new')args.push('--fork-session')
    const name=optionValue(input.session_name);if(name)args.push('--name',name)
  }else if(provider==='gemini'){
    if(resume!=='new')throw new Error('La reprise Gemini n’est pas encore exposée de façon sûre par Orchestrator.')
    if(model)args.push('--model',model)
    if(input.sandbox)args.push('--sandbox')
    if(['default','auto_edit','yolo'].includes(input.approval_mode))args.push('--approval-mode',input.approval_mode)
  }else if(provider==='opencode'){
    if(resume!=='new')throw new Error('La reprise OpenCode n’est pas encore exposée de façon sûre par Orchestrator.')
    if(model)args.push('--model',model)
  }else if(provider==='copilot'){
    if(resume!=='new')throw new Error('La reprise Copilot n’est pas encore exposée de façon sûre par Orchestrator.')
    if(model)args.push('--model',model)
    if(input.allow_all||dangerous)args.push('--allow-all')
  }else throw new Error('Unsupported terminal provider.')
  if(prompt)args.push(prompt)
  return args
}
const row=value=>{const active=sessions.has(value.uid);return{...value,status:active&&value.status==='interrupted'?'running':value.status,metadata:json.read(value.metadata,{}),active,attachable:active}}
const projectRoot=project=>String(project?.description||'').match(/Repository:\s*(.+)/i)?.[1]?.trim()||null
const flush=session=>{if(!session.pending)return;const content=session.pending;session.pending='';base().prepare('INSERT INTO terminal_chunks(session_id,sequence,stream,content,created_at) VALUES((SELECT id FROM terminal_sessions WHERE uid=?),?,?,?,?)').run(session.uid,++session.sequence,'pty',content,nowStamp())}
const scheduleFlush=session=>{if(session.flushTimer)return;session.flushTimer=setTimeout(()=>{session.flushTimer=null;flush(session)},200);session.flushTimer.unref?.()}
const publish=(session,message)=>{for(const socket of session.clients)if(socket.readyState===1)socket.send(JSON.stringify(message))}
const plainTerminalOutput=value=>String(value||'').replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'').replace(/\r/g,'')
const submitTerminalMessage=(session,message)=>{session.interactiveReady=false;session.pty.write(message);setTimeout(()=>session.pty.write('\r'),180);setTimeout(()=>session.pty.write('\r'),700);clearTimeout(session.messageTimer);session.messageTimer=setTimeout(()=>{session.interactiveReady=true;flushInputQueue(session)},1100);session.messageTimer.unref?.()}
const flushInputQueue=session=>{if(!session.interactiveReady||session.startupPending||!session.inputQueue.length)return;submitTerminalMessage(session,session.inputQueue.shift())}

export function terminalProviders(){const detected=detectedProviderModels(),capabilities={codex:{resume:true,dangerous_bypass:true,model:true,sandbox:['read-only','workspace-write','danger-full-access'],approval:['untrusted','on-request','never'],search:true},claude:{resume:true,dangerous_bypass:true,model:true,permission_modes:['acceptEdits','auto','manual','dontAsk','plan'],fork_session:true},gemini:{resume:false,dangerous_bypass:true,model:true,approval_modes:['default','auto_edit','yolo'],sandbox:true},opencode:{resume:false,dangerous_bypass:false,model:true,permission_environment:true},copilot:{resume:false,dangerous_bypass:true,model:true,allow_all:true}};return Object.keys(commandCandidates).map(id=>({id,label:providerLabels[id],available:Boolean(executable(id)),command:executable(id),models:detected[id].models,default_model:detected[id].default_model,default_effort:detected[id].default_effort,capabilities:{...capabilities[id],efforts:detected[id].efforts},permission_profiles:permissionProfiles}))}
export function terminalSessions({limit=100}={}){return base().prepare('SELECT t.*,p.slug project_slug,p.name project_name FROM terminal_sessions t LEFT JOIN projects p ON p.id=t.project_id ORDER BY t.created_at DESC LIMIT ?').all(Math.max(1,Math.min(500,Number(limit)||100))).map(row)}
export function terminalSession(sessionUid){const value=base().prepare('SELECT t.*,p.slug project_slug,p.name project_name FROM terminal_sessions t LEFT JOIN projects p ON p.id=t.project_id WHERE t.uid=?').get(sessionUid);return value?row(value):null}
export function terminalTranscript(sessionUid,{after=0,limit=2000}={}){const session=base().prepare('SELECT id FROM terminal_sessions WHERE uid=?').get(sessionUid);if(!session)return null;return base().prepare('SELECT sequence,stream,content,created_at FROM terminal_chunks WHERE session_id=? AND sequence>? ORDER BY sequence LIMIT ?').all(session.id,Number(after)||0,Math.max(1,Math.min(10000,Number(limit)||2000)))}
export function terminalTranscriptTail(sessionUid,{limit=1200}={}){const session=base().prepare('SELECT id FROM terminal_sessions WHERE uid=?').get(sessionUid);if(!session)return null;return base().prepare('SELECT sequence,stream,content,created_at FROM terminal_chunks WHERE session_id=? ORDER BY sequence DESC LIMIT ?').all(session.id,Math.max(1,Math.min(3000,Number(limit)||1200))).reverse()}
export function terminalTranscriptCharacters(sessionUid){const session=base().prepare('SELECT id FROM terminal_sessions WHERE uid=?').get(sessionUid);if(!session)return 0;return Number(base().prepare('SELECT COALESCE(SUM(LENGTH(content)),0) total FROM terminal_chunks WHERE session_id=?').get(session.id)?.total)||0}
export function onTerminalExit(listener){if(typeof listener!=='function')return()=>{};exitListeners.add(listener);return()=>exitListeners.delete(listener)}
export function onTerminalCheckpoint(listener){if(typeof listener!=='function')return()=>{};checkpointListeners.add(listener);return()=>checkpointListeners.delete(listener)}
const attachmentTypes=new Map([['image/png','.png'],['image/jpeg','.jpg'],['image/webp','.webp'],['image/gif','.gif'],['text/plain','.txt'],['text/markdown','.md'],['text/csv','.csv'],['text/html','.html'],['text/css','.css'],['text/xml','.xml'],['application/xml','.xml'],['application/json','.json'],['application/pdf','.pdf'],['application/javascript','.js'],['text/javascript','.js'],['application/vnd.openxmlformats-officedocument.wordprocessingml.document','.docx'],['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.xlsx'],['application/vnd.openxmlformats-officedocument.presentationml.presentation','.pptx']])
const safeAttachmentExtensions=new Set(['.txt','.md','.csv','.html','.css','.scss','.xml','.json','.yaml','.yml','.toml','.ini','.log','.js','.jsx','.ts','.tsx','.vue','.php','.py','.rb','.java','.kt','.swift','.go','.rs','.c','.cc','.cpp','.h','.hpp','.cs','.shader','.sql','.sh'])
const watchedImageExtensions=new Set(['.png','.jpg','.jpeg','.webp','.gif','.svg'])
export function addTerminalAttachment(sessionUid,input={}){const db=base(),stored=db.prepare('SELECT metadata FROM terminal_sessions WHERE uid=?').get(sessionUid);if(!stored)throw Object.assign(new Error('Unknown terminal session.'),{status:404});const original=String(input.name||'fichier').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)||'fichier',originalExtension=extname(original).toLowerCase(),match=String(input.data_url||'').match(/^data:([a-z0-9.+-]+\/[a-z0-9.+-]+);base64,([A-Za-z0-9+/=]+)$/i),declaredMime=match?.[1]?.toLowerCase(),mappedExtension=attachmentTypes.get(declaredMime),extension=mappedExtension||(declaredMime==='application/octet-stream'&&safeAttachmentExtensions.has(originalExtension)?originalExtension:null);if(!match||!extension)throw Object.assign(new Error('Ce format n’est pas accepté. Utilisez une image, un PDF, un document Office ou un fichier texte/source pris en charge.'),{status:400});const buffer=Buffer.from(match[2],'base64');if(!buffer.length||buffer.length>8*1024*1024)throw Object.assign(new Error('La pièce jointe doit peser entre 1 octet et 8 Mo.'),{status:413});const mime=declaredMime==='application/octet-stream'?assetMime(original):declaredMime,attachmentUid=uid(),stem=original.replace(/\.[^.]+$/,'')||'fichier',directory=join(dirname(dbPath()),'session-uploads',sessionUid),path=join(directory,`${attachmentUid}-${stem}${extension}`);mkdirSync(directory,{recursive:true,mode:0o700});writeFileSync(path,buffer,{mode:0o600});const metadata=json.read(stored.metadata,{}),attachment={uid:attachmentUid,name:original,mime,bytes:buffer.length,path,type:mime.startsWith('image/')?'image':'file',sha256:createHash('sha256').update(buffer).digest('hex'),created_at:nowStamp()};metadata.attachments=[...(metadata.attachments||[]),attachment];db.prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(metadata),nowStamp(),sessionUid);return attachment}
export function terminalAttachment(sessionUid,attachmentUid){const session=terminalSession(sessionUid),attachment=session?.metadata?.attachments?.find(item=>item.uid===attachmentUid);if(!attachment)return null;try{const root=realpathSync(join(dirname(dbPath()),'session-uploads',sessionUid)),path=realpathSync(attachment.path);if(!path.startsWith(`${root}/`)||!statSync(path).isFile())return null;return{...attachment,path}}catch{return null}}
export function terminalReportArtifacts(sessionUid){const live=sessions.get(sessionUid);if(live)flush(live);const session=terminalSession(sessionUid);if(!session)return[];const directory=join(dirname(dbPath()),'session-uploads',sessionUid);mkdirSync(directory,{recursive:true,mode:0o700});const transcript=terminalTranscript(sessionUid,{limit:10000}).map(chunk=>chunk.content).join('').replace(/\u001b\[[0-?]*[ -/]*[@-~]/g,'').replace(/\r/g,''),path=join(directory,'transcript.txt'),buffer=Buffer.from(transcript||'[Aucune sortie enregistrée]\n','utf8');writeFileSync(path,buffer,{mode:0o600});const transcriptArtifact={uid:uid(),name:'transcript.txt',label:`Transcription · ${session.title}`,type:'report',mime:'text/plain',bytes:buffer.length,path,sha256:createHash('sha256').update(buffer).digest('hex'),created_at:nowStamp(),source:'result'},artifacts=[transcriptArtifact],seen=new Set([realpathSync(path)]);for(const item of terminalSessionAssets(sessionUid)){let assetPath,stat;try{assetPath=realpathSync(item.path);stat=statSync(assetPath)}catch{continue}if(seen.has(assetPath)||!stat.isFile()||stat.size>50*1024*1024)continue;seen.add(assetPath);const mime=item.mime||assetMime(assetPath),image=/^image\//.test(mime),attachment=(session.metadata?.attachments||[]).some(value=>{try{return realpathSync(value.path)===assetPath}catch{return false}}),contents=readFileSync(assetPath);artifacts.push({...item,uid:item.uid||uid(),name:item.name||basename(assetPath),label:attachment?`${image?'Image':'Fichier'} de session · ${item.name||basename(assetPath)}`:`${image?'Image liée':'Fichier lié'} · ${item.label||item.name||basename(assetPath)}`,type:image?'screenshot':'file',mime,bytes:stat.size,path:assetPath,sha256:createHash('sha256').update(contents).digest('hex'),created_at:item.created_at||nowStamp(),source:attachment?'user':item.source||'detected'})}const metadata={...session.metadata,report_artifacts:artifacts};base().prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(metadata),nowStamp(),sessionUid);return artifacts}
const assetMime=path=>({'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif','.svg':'image/svg+xml','.txt':'text/plain','.md':'text/markdown','.csv':'text/csv','.html':'text/html','.css':'text/css','.scss':'text/plain','.xml':'application/xml','.json':'application/json','.yaml':'text/plain','.yml':'text/plain','.toml':'text/plain','.ini':'text/plain','.log':'text/plain','.js':'text/javascript','.jsx':'text/javascript','.ts':'text/plain','.tsx':'text/plain','.vue':'text/plain','.php':'text/plain','.py':'text/plain','.rb':'text/plain','.java':'text/plain','.kt':'text/plain','.swift':'text/plain','.go':'text/plain','.rs':'text/plain','.c':'text/plain','.cc':'text/plain','.cpp':'text/plain','.h':'text/plain','.hpp':'text/plain','.cs':'text/plain','.shader':'text/plain','.sql':'text/plain','.sh':'text/plain','.pdf':'application/pdf','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.pptx':'application/vnd.openxmlformats-officedocument.presentationml.presentation'}[extname(path).toLowerCase()]||'application/octet-stream')
export function terminalSessionAssets(sessionUid){const session=terminalSession(sessionUid);if(!session)return[];const known=new Map(),add=item=>{if(!item?.path||known.has(item.path))return;try{const path=realpathSync(item.path),stat=statSync(path);if(!stat.isFile())return;known.set(path,{uid:item.uid||createHash('sha256').update(path).digest('hex').slice(0,24),name:item.name||basename(path),label:item.label||item.name||basename(path),path,mime:item.mime||assetMime(path),bytes:item.bytes??stat.size,source:item.source||'detected',type:item.type||(/^image\//.test(item.mime||assetMime(path))?'image':'file')})}catch{}};for(const collection of [session.metadata?.report_artifacts,session.metadata?.attachments,session.metadata?.inherited_assets,session.metadata?.detected_assets])for(const item of collection||[])add({...item,source:item.source||(item.type==='report'?'result':'user')});const transcript=terminalTranscriptTail(sessionUid,{limit:1200}).map(chunk=>chunk.content).join('').replace(/\u001b\[[0-?]*[ -/]*[@-~]/g,'');for(const match of transcript.matchAll(/(?:^|[\s`'"(])((?:\/)?(?:[A-Za-z0-9_.-]+\/)+[A-Za-z0-9_.-]+\.[A-Za-z0-9]{1,12})/gm)){try{const cited=match[1],path=realpathSync(isAbsolute(cited)?cited:join(session.cwd,cited));if(path===session.cwd||!path.startsWith(`${session.cwd}/`))continue;add({path,name:cited,label:isAbsolute(cited)?relative(session.cwd,path):cited,source:'detected'})}catch{}}return[...known.values()]}
export function terminalSessionAsset(sessionUid,assetUid){return terminalSessionAssets(sessionUid).find(item=>item.uid===assetUid)||null}
export function detectTerminalNativeSession(sessionUid){const session=terminalSession(sessionUid);if(!session)return null;const roots=session.provider==='codex'?[join(homedir(),'.codex','sessions'),join(homedir(),'.codex','archived_sessions')] :session.provider==='claude'?[join(homedir(),'.claude','projects')]:[],started=new Date(session.started_at||session.created_at).getTime(),agentName=String(session.metadata?.pilot_agent_name||''),markers=session.metadata?.pilot_parent_session_uid&&agentName?[`Tu es le sous-agent « ${agentName} »`]:session.metadata?.pilot_role==='coordinator'?['Tu es le pilote persistant','Tu es la relève contextuelle']:[],stored=String(session.metadata?.native_session_id||'');if(stored)return stored;const claimed=new Set(base().prepare('SELECT uid,metadata FROM terminal_sessions WHERE uid<>?').all(sessionUid).map(row=>json.read(row.metadata,{}).native_session_id).filter(Boolean)),candidates=[];for(const root of roots)for(const path of recentJsonl(root)){let lines;try{lines=headText(path).split('\n').slice(0,30)}catch{continue}for(const line of lines){let value;try{value=JSON.parse(line)}catch{continue}const payload=value.payload||value,cwd=payload.cwd||value.cwd,id=payload.id||payload.sessionId||value.sessionId||basename(path,'.jsonl'),stamp=value.timestamp||payload.timestamp;if(cwd!==session.cwd||!id)continue;const content=value.message?.content||payload.message?.content||payload.content||'',initialText=Array.isArray(content)?content.map(item=>item?.text||'').join('\n'):String(content),delta=Math.abs(new Date(stamp||statSync(path).birthtime).getTime()-started);if(delta<=10*60*1000)candidates.push({id:String(id),delta,matched:!markers.length||markers.some(marker=>initialText.includes(marker)),claimed:claimed.has(String(id))});break}}const native=candidates.sort((a,b)=>Number(b.matched)-Number(a.matched)||Number(a.claimed)-Number(b.claimed)||a.delta-b.delta)[0]?.id||null;if(native){const metadata={...session.metadata,native_session_id:native};base().prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(metadata),nowStamp(),sessionUid)}return native}
export function terminalLatestAssistantText(sessionUid){const session=terminalSession(sessionUid),native=detectTerminalNativeSession(sessionUid);if(!session||!native)return null;const roots=session.provider==='codex'?[join(homedir(),'.codex','sessions'),join(homedir(),'.codex','archived_sessions')] :session.provider==='claude'?[join(homedir(),'.claude','projects')]:[],direct=session.provider==='claude'?join(homedir(),'.claude','projects',session.cwd.replace(/[^a-zA-Z0-9_-]/g,'-'),`${native}.jsonl`):null,cached=nativeTranscriptCache.get(native),path=cached&&existsSync(cached)?cached:direct&&existsSync(direct)?direct:roots.flatMap(root=>recentJsonl(root)).find(candidate=>basename(candidate,'.jsonl')===native);if(!path)return null;nativeTranscriptCache.set(native,path);let lines;try{lines=tailText(path,4*1024*1024).split('\n').reverse()}catch{return null}for(const line of lines){let value;try{value=JSON.parse(line)}catch{continue}const payload=value.payload||value,message=value.message||payload.message||payload;if(message?.role!=='assistant'&&!(payload.type==='message'&&payload.role==='assistant'))continue;const content=message.content||payload.content,text=Array.isArray(content)?content.map(item=>item?.text||item?.output_text||'').filter(Boolean).join('\n'):typeof content==='string'?content:'';if(text.trim())return text.trim()}return null}
export function terminalNativeConversation(sessionUid,{limit=100}={}){const session=terminalSession(sessionUid),native=detectTerminalNativeSession(sessionUid);if(!session||!native)return null;const roots=session.provider==='codex'?[join(homedir(),'.codex','sessions'),join(homedir(),'.codex','archived_sessions')]:session.provider==='claude'?[join(homedir(),'.claude','projects')]:[],direct=session.provider==='claude'?join(homedir(),'.claude','projects',session.cwd.replace(/[^a-zA-Z0-9_-]/g,'-'),`${native}.jsonl`):null,cached=nativeTranscriptCache.get(native),path=cached&&existsSync(cached)?cached:direct&&existsSync(direct)?direct:roots.flatMap(root=>recentJsonl(root)).find(candidate=>basename(candidate,'.jsonl')===native);if(!path)return[];nativeTranscriptCache.set(native,path);let lines;try{lines=tailText(path,8*1024*1024).split('\n')}catch{return[]}const messages=[];for(const line of lines){let value;try{value=JSON.parse(line)}catch{continue}const payload=value.payload||value,message=value.message||payload.message||payload,role=message?.role||payload.role;if(role!=='user'&&role!=='assistant')continue;const content=message.content??payload.content,text=Array.isArray(content)?content.filter(item=>['text','input_text','output_text'].includes(String(item?.type||''))).map(item=>item?.text||item?.input_text||item?.output_text||'').filter(Boolean).join('\n'):typeof content==='string'?content:'';if(!text.trim())continue;const normalized=text.trim(),previous=messages.at(-1);if(previous?.role===role&&previous.content===normalized)continue;messages.push({uid:createHash('sha256').update(`${native}:${value.uuid||value.id||messages.length}:${role}:${normalized}`).digest('hex').slice(0,24),role,content:normalized,created_at:value.timestamp||payload.timestamp||session.created_at})}return messages.slice(-Math.max(1,Math.min(500,Number(limit)||100)))}
export function resumeTerminalSession(sessionUid,input={}){const previous=terminalSession(sessionUid);if(!previous)throw Object.assign(new Error('Unknown terminal session.'),{status:404});if(previous.active)throw Object.assign(new Error('This terminal session is already active.'),{status:409});const nativeSessionId=detectTerminalNativeSession(sessionUid);if(!nativeSessionId)throw Object.assign(new Error('The native Codex or Claude history could not be identified safely.'),{status:409});const launch={...(previous.metadata?.launch_options||{})};delete launch.prompt;if(previous.metadata?.pilot_role==='coordinator'&&!previous.metadata?.pilot_parent_session_uid)delete launch.disable_tools;const activeRoot=previous.metadata?.pilot_parent_session_uid?terminalSessions({limit:500}).find(row=>row.active&&row.metadata?.pilot_uid===previous.metadata.pilot_uid&&row.metadata?.pilot_run_uid===previous.metadata.pilot_run_uid&&!row.metadata?.pilot_parent_session_uid):null,pilot=previous.metadata?.pilot_uid?{uid:previous.metadata.pilot_uid,run_uid:previous.metadata.pilot_run_uid,role:previous.metadata.pilot_role,agent_name:previous.metadata.pilot_agent_name,agent_role:previous.metadata.pilot_agent_role,parent_session_uid:activeRoot?.uid||previous.metadata.pilot_parent_session_uid}:null,resumed=createTerminalSession({provider:previous.provider,project:previous.project_slug||null,cwd:previous.project_slug?undefined:previous.cwd,title:previous.title,objective:previous.metadata?.objective_uid||null,pass:previous.metadata?.pass_uid?{uid:previous.metadata.pass_uid,source:'session_resume'}:null,pilot,context:{gdd_chapter_key:previous.metadata?.gdd_chapter_key||null},options:{...launch,resume_mode:'id',resume_id:nativeSessionId,prompt:String(input.prompt||'').trim()||undefined},cols:previous.metadata?.cols||120,rows:previous.metadata?.rows||34});const childMetadata={...resumed.metadata,resumed_from_uid:previous.uid,native_session_id:nativeSessionId,resume_depth:Number(previous.metadata?.resume_depth||0)+1,rotation_index:Number(previous.metadata?.rotation_index||0),handoff_key:previous.metadata?.handoff_key||null,inherited_assets:terminalSessionAssets(previous.uid)},previousMetadata={...previous.metadata,resumed_by_uid:resumed.uid,native_session_id:nativeSessionId};base().prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(childMetadata),nowStamp(),resumed.uid);base().prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(previousMetadata),nowStamp(),previous.uid);return{...terminalSession(resumed.uid),attach_token:resumed.attach_token}}
export function markTerminalReported(sessionUid,eventUid){const db=base(),stored=db.prepare('SELECT metadata FROM terminal_sessions WHERE uid=?').get(sessionUid);if(!stored)return null;const metadata={...json.read(stored.metadata,{}),reported_at:nowStamp(),reported_event_uid:eventUid,report_status:'awaiting_verification'};db.prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(metadata),nowStamp(),sessionUid);return terminalSession(sessionUid)}
export function linkTerminalObjective(sessionUid,objectiveUid,source='session_handoff'){const db=base(),stored=db.prepare('SELECT project_id,metadata FROM terminal_sessions WHERE uid=?').get(sessionUid);if(!stored)throw Object.assign(new Error('Unknown terminal session.'),{status:404});if(!stored.project_id)throw Object.assign(new Error('This session is not linked to a project.'),{status:409});const objective=db.prepare('SELECT uid,title,status,priority FROM objectives WHERE project_id=? AND uid=?').get(stored.project_id,objectiveUid);if(!objective)throw Object.assign(new Error('Unknown objective for this project.'),{status:404});const current=json.read(stored.metadata,{}),metadata={...current,objective_uid:objective.uid,objective_title:objective.title,objective_status_at_launch:objective.status,objective_priority_at_launch:objective.priority,pass_uid:current.pass_uid||uid(),pass_source:current.pass_source||source};db.prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write(metadata),nowStamp(),sessionUid);return terminalSession(sessionUid)}
export function createTerminalSession(input={}){
  const requestedProvider=String(input.provider||'').toLowerCase()
  if(!Object.hasOwn(commandCandidates,requestedProvider))throw Object.assign(new Error('Unsupported AI provider.'),{status:400})
  const routing=input.routing||((input.options?.resume_mode||'new')==='new'?routeAiProvider(requestedProvider,{available:value=>Boolean(executable(value))}):{provider:requestedProvider,requested:requestedProvider,switched:false,reason:null}),provider=routing.provider,command=executable(provider)
  if(!command)throw Object.assign(new Error(`${providerLabels[provider]||provider} is not available on this machine.`),{status:409})
  const project=input.project?base().prepare('SELECT * FROM projects WHERE slug=? OR uid=?').get(input.project,input.project):null
  if(input.project&&!project)throw Object.assign(new Error('Unknown project.'),{status:404})
  const objective=input.objective&&project?base().prepare('SELECT uid,title,status,priority FROM objectives WHERE project_id=? AND uid=?').get(project.id,input.objective):null
  if(input.objective&&!project)throw Object.assign(new Error('An objective-linked session requires a project.'),{status:400})
  if(input.objective&&!objective)throw Object.assign(new Error('Unknown objective for this project.'),{status:404})
  const requested=String(input.cwd||projectRoot(project)||process.cwd()),cwd=realpathSync(requested)
  if(!statSync(cwd).isDirectory())throw new Error('Terminal working directory must be a directory.')
  const sessionUid=uid(),attachToken=randomBytes(32).toString('hex'),createdAt=nowStamp(),title=String(input.title||`${providerLabels[provider]||provider} · ${project?.name||cwd.split('/').at(-1)}`).trim().slice(0,160)
  const rawOptions=routing.switched?{...(input.options||{}),model:undefined}:input.options||{},effectiveOptions=resolvePermissionOptions(provider,rawOptions,project,input.permission_profile),detected=detectedProviderModels()[provider],args=terminalArguments(provider,effectiveOptions)
  const passUid=objective?(input.pass?.uid||input.pilot?.run_uid||uid()):null
  base().prepare("INSERT INTO terminal_sessions(uid,project_id,provider,title,cwd,status,command_path,created_at,updated_at,metadata) VALUES(?,?,?,?,?,'starting',?,?,?,?)").run(sessionUid,project?.id||null,provider,title,cwd,command,createdAt,createdAt,json.write({cols:Number(input.cols)||120,rows:Number(input.rows)||32,arguments:args,launch_options:{...effectiveOptions,prompt:effectiveOptions.prompt?'[provided]':null},permission_profile:effectiveOptions.permission_profile||null,resolved_model:effectiveOptions.model||detected.default_model||null,resolved_effort:effectiveOptions.effort||detected.default_effort||null,provider_switched_from:routing.switched?routing.requested:null,provider_switch_reason:routing.reason||null,pilot_uid:input.pilot?.uid||null,pilot_run_uid:input.pilot?.run_uid||null,pilot_role:input.pilot?.role||null,pilot_agent_name:input.pilot?.agent_name||null,pilot_agent_role:input.pilot?.agent_role||null,pilot_parent_session_uid:input.pilot?.parent_session_uid||null,objective_uid:objective?.uid||null,objective_title:objective?.title||null,objective_status_at_launch:objective?.status||null,objective_priority_at_launch:objective?.priority??null,pass_uid:passUid,pass_source:objective?String(input.pass?.source||input.context?.source||'direct').slice(0,80):null,gdd_chapter_key:objective?String(input.context?.gdd_chapter_key||'').slice(0,160)||null:null}))
  const providerEnv=provider==='opencode'&&effectiveOptions.opencode_permissions?{OPENCODE_PERMISSION:JSON.stringify(effectiveOptions.opencode_permissions)}:{},utf8Locale=process.env.LC_CTYPE||process.env.LANG||'en_US.UTF-8',pty=spawn(command,args,{name:'xterm-256color',cols:Math.max(40,Number(input.cols)||120),rows:Math.max(10,Number(input.rows)||32),cwd,env:{...process.env,...providerEnv,LANG:utf8Locale,LC_CTYPE:utf8Locale,TERM:'xterm-256color',COLORTERM:'truecolor'}})
  const session={uid:sessionUid,provider,pty,attachToken,clients:new Set(),pending:'',sequence:0,flushTimer:null,checkpointTimer:null,assetWatcher:null,assetTimers:new Map(),inputQueue:[],startupSeen:false,startupPending:false,interactiveReady:provider!=='codex',createdAtMs:Date.now(),readyTimer:null,messageTimer:null}
  if(provider==='codex'){session.readyTimer=setTimeout(()=>{session.interactiveReady=true;session.startupPending=false;flushInputQueue(session)},20000);session.readyTimer.unref?.()}
  sessions.set(sessionUid,session)
  base().prepare("UPDATE terminal_sessions SET status='running',pid=?,started_at=?,updated_at=? WHERE uid=?").run(pty.pid,createdAt,createdAt,sessionUid)
  try{session.assetWatcher=watch(cwd,{recursive:true},(_event,filename)=>{if(!filename||!watchedImageExtensions.has(extname(String(filename)).toLowerCase()))return;const key=String(filename),previous=session.assetTimers.get(key);if(previous)clearTimeout(previous);const timer=setTimeout(()=>{session.assetTimers.delete(key);try{const path=realpathSync(join(cwd,key)),stat=statSync(path);if(!stat.isFile()||path===cwd||!path.startsWith(`${cwd}/`))return;const stored=base().prepare('SELECT metadata FROM terminal_sessions WHERE uid=?').get(sessionUid),metadata=json.read(stored?.metadata,{}),current=Array.isArray(metadata.detected_assets)?metadata.detected_assets:[],fingerprint=`${path}:${stat.size}:${stat.mtimeMs}`;if(current.some(item=>item.fingerprint===fingerprint))return;const item={uid:createHash('sha256').update(path).digest('hex').slice(0,24),name:basename(path),label:relative(cwd,path),path,mime:assetMime(path),bytes:stat.size,source:'result',type:'image',fingerprint,created_at:nowStamp()},detected=[item,...current.filter(asset=>asset.path!==path)].slice(0,200);base().prepare('UPDATE terminal_sessions SET metadata=?,updated_at=? WHERE uid=?').run(json.write({...metadata,detected_assets:detected}),nowStamp(),sessionUid);publish(session,{type:'assets_changed'})}catch{}},180);timer.unref?.();session.assetTimers.set(key,timer)})}catch{}
  pty.onData(content=>{session.pending+=content;scheduleFlush(session);publish(session,{type:'output',content});clearTimeout(session.checkpointTimer);session.checkpointTimer=setTimeout(()=>{flush(session);const transcript=terminalTranscript(sessionUid,{limit:10000})?.map(chunk=>chunk.content).join('')||'';for(const listener of checkpointListeners)try{listener({session:terminalSession(sessionUid),transcript})}catch{}},1800);session.checkpointTimer.unref?.();if(provider==='codex'){const plain=plainTerminalOutput(content);if(/Starting MCP servers/i.test(plain)){session.startupSeen=true;session.startupPending=true;session.interactiveReady=false}const startupDone=session.startupSeen&&session.startupPending&&/MCP startup interrupted/i.test(plain),ordinaryPrompt=!session.startupSeen&&Date.now()-session.createdAtMs>5000&&/Ask Codex to do anything/i.test(plain),returnPrompt=session.startupSeen&&!session.startupPending&&/Ask Codex to do anything/i.test(plain);if(startupDone||ordinaryPrompt||returnPrompt){session.startupPending=false;clearTimeout(session.readyTimer);setTimeout(()=>{session.interactiveReady=true;flushInputQueue(session)},300)}}})
  pty.onExit(({exitCode,signal})=>{flush(session);clearTimeout(session.readyTimer);clearTimeout(session.messageTimer);clearTimeout(session.checkpointTimer);session.assetWatcher?.close();for(const timer of session.assetTimers.values())clearTimeout(timer);session.assetTimers.clear();sessions.delete(sessionUid);const stamp=nowStamp(),current=base().prepare('SELECT status FROM terminal_sessions WHERE uid=?').get(sessionUid),status=current?.status==='stopped'?'stopped':exitCode===0?'completed':'failed';base().prepare("UPDATE terminal_sessions SET status=?,exit_code=?,signal=?,ended_at=?,updated_at=? WHERE uid=?").run(status,exitCode,signal,stamp,stamp,sessionUid);const finished=terminalSession(sessionUid),transcript=terminalTranscript(sessionUid,{limit:10000})?.map(chunk=>chunk.content).join('')||'';for(const listener of exitListeners)try{listener({session:finished,transcript,status,exitCode,signal})}catch{}publish(session,{type:'exit',exitCode,signal,status});for(const socket of session.clients)socket.close(1000,'Terminal exited')})
  return{...terminalSession(sessionUid),attach_token:attachToken}
}
export function stopTerminalSession(sessionUid){const session=sessions.get(sessionUid);if(!session)return terminalSession(sessionUid);base().prepare("UPDATE terminal_sessions SET status='stopped',updated_at=? WHERE uid=?").run(nowStamp(),sessionUid);session.pty.kill();return terminalSession(sessionUid)}
export function sendTerminalInput(sessionUid,content){const session=sessions.get(sessionUid),value=String(content||'').trim();if(!session||!value)return false;if(!session.interactiveReady||session.startupPending)session.inputQueue.push(value);else submitTerminalMessage(session,value);return true}
export function terminalAttachToken(sessionUid){const session=sessions.get(sessionUid);if(!session)return null;session.attachToken=randomBytes(32).toString('hex');return{session:terminalSession(sessionUid),attach_token:session.attachToken}}
export function markInterruptedSessions(){base().prepare("UPDATE terminal_sessions SET status='interrupted',ended_at=?,updated_at=? WHERE status IN ('starting','running')").run(nowStamp(),nowStamp())}
export function attachTerminalWebSockets(server){
  const websocket=new WebSocketServer({noServer:true})
  server.on('upgrade',(request,socket,head)=>{let url;try{url=new URL(request.url,'http://127.0.0.1')}catch{socket.destroy();return}const origin=request.headers.origin,forwardedProto=String(request.headers['x-forwarded-proto']||'').split(',')[0].trim(),expected=`${forwardedProto||'http'}://${request.headers.host}`;if(origin&&origin!==expected){socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');socket.destroy();return}const match=url.pathname.match(/^\/api\/terminal\/sessions\/([^/]+)\/stream$/);if(!match){socket.destroy();return}const session=sessions.get(decodeURIComponent(match[1]));if(!session||url.searchParams.get('token')!==session.attachToken){socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');socket.destroy();return}websocket.handleUpgrade(request,socket,head,client=>websocket.emit('connection',client,session))})
  websocket.on('connection',(socket,session)=>{session.clients.add(socket);socket.send(JSON.stringify({type:'ready',session:terminalSession(session.uid)}));socket.on('message',raw=>{let message;try{message=JSON.parse(raw.toString())}catch{return}if(message.type==='input'&&typeof message.content==='string')session.pty.write(message.content.slice(0,65536));if(message.type==='message'&&typeof message.content==='string'){const content=message.content.slice(0,65536).trim();if(content)submitTerminalMessage(session,content)}if(message.type==='resize'){const cols=Math.max(40,Math.min(400,Number(message.cols)||120)),rows=Math.max(10,Math.min(200,Number(message.rows)||32));session.pty.resize(cols,rows)}});socket.on('close',()=>session.clients.delete(socket))})
  return websocket
}
